### We'll read the files downloaded by download_test1.sh, which consists of a relatively small size matrix.

In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
from math import exp, ceil, log
import pandas as pd
from numpy.linalg import norm, qr, cholesky, inv, svd, matrix_rank, lstsq, cond


In [3]:
def readData(filename, size=784, save=True):
    '''
    Read MNIST sparse data from filename
    and transforms this into a dense
    matrix, each line representing an entry
    of the database (i.e. a "flattened" image)
    '''
    print(filename)
    # Specify dtype to ensure floating-point numbers are read
    dataR = pd.read_csv(filename, sep=',', header=None, dtype=str)
    n = len(dataR)
    data = np.zeros((n, size))
    labels = np.zeros((n, 1))
    # Format accordingly
    for i in range(n):
        l = dataR.iloc[i, 0]
        labels[i] = float(l[0])  # Convert label to float
        l = l[2:]
        indices_values = [tuple(map(float, pair.split(':'))) for pair in l.split()]
        # Separate indices and values
        indices, values = zip(*indices_values)
        indices = [int(i) for i in indices]
        # Fill in the values at the specified indices
        data[i, indices] = values
    if save:
        np.savetxt('./denseData_test1.csv', data, delimiter=',', fmt='%10.5f')
        np.savetxt('./labels_test1.csv', labels, delimiter=',', fmt='%10.5f')
    return data, labels

In [4]:
data, labels = readData('mnist_780')
print("data[:5,:5] is\n",data[:5,:5])
np.save("MNIST_780_test1.npy", data)

mnist_780
data[:5,:5] is
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
def build_MNIST_matrixA (mnistData, dimension_n, value_c, save = True, 
                         file_name = "A_3_dataset_2_mnist.npy"):
    '''
    this is the function that builds the matrix A based on 
    MNIST dataset with RBF specified in the project requirement 
    INPUT: 
        - mnistData is obtained from MNIST dataset
        - dimension_n will define the size of the output square matrix, 
            it depends on memory consumption
        - value_c can be varied
    OUTPUT: we'll save the matrix of dimension_n**2 using pickle 
    '''
    outputMatrix = np.zeros((dimension_n, dimension_n))
    for j in range(dimension_n):
        for i in range(j):
            outputMatrix[i, j] = exp(( - norm(mnistData[i,:] - mnistData[j,:]) ** 2) / (value_c ** 2))
    outputMatrix = outputMatrix + np.transpose(outputMatrix)
    np.fill_diagonal(outputMatrix, 1.0)
    if save: 
        np.save(file_name, outputMatrix) 


In [5]:
build_MNIST_matrixA(data, 1024, 100)
loadMatrix = np.load("A_3_dataset_2_mnist.npy")
print(loadMatrix[:10,:5])
print(loadMatrix.shape)

[[1.         0.99127504 0.98824289 0.99001237 0.98907651]
 [0.99127504 1.         0.98715919 0.98829865 0.98930957]
 [0.98824289 0.98715919 1.         0.9898814  0.98994457]
 [0.99001237 0.98829865 0.9898814  1.         0.99126262]
 [0.98907651 0.98930957 0.98994457 0.99126262 1.        ]
 [0.98979753 0.98903161 0.98938555 0.99024257 0.99195122]
 [0.99100754 0.98756737 0.98972827 0.991512   0.9925866 ]
 [0.99278471 0.98967594 0.98934556 0.98962114 0.98935745]
 [0.99136177 0.98870132 0.99122707 0.99290202 0.9940263 ]
 [0.98989935 0.98824599 0.99277739 0.99119833 0.99174104]]
(1024, 1024)


In [8]:
build_MNIST_matrixA(mnistData = data, dimension_n = 1024, value_c = 10, 
                    file_name = "A_3_dataset_2_mnist_C=10.npy")
loadMatrix2 = np.load("A_3_dataset_2_mnist_C=10.npy")
print(loadMatrix2[:10,:5])
print(loadMatrix2.shape)

[[1.         0.41631015 0.30645728 0.36649001 0.33341767]
 [0.41631015 1.         0.27461183 0.3081913  0.34136674]
 [0.30645728 0.27461183 1.         0.36167314 0.36398875]
 [0.36649001 0.3081913  0.36167314 1.         0.4157891 ]
 [0.33341767 0.34136674 0.36398875 0.4157891  1.        ]
 [0.35862154 0.33190771 0.34399823 0.37511058 0.44568853]
 [0.40522463 0.28620227 0.35612081 0.42638049 0.47516109]
 [0.48473926 0.35424295 0.34261053 0.3522868  0.34302277]
 [0.41996868 0.32100455 0.41430039 0.49050064 0.54927192]
 [0.36232966 0.30655351 0.48438198 0.41310095 0.43634339]]
(1024, 1024)


In [6]:
build_MNIST_matrixA(mnistData=data, 
                    dimension_n=65536, 
                    value_c=1000,
                    file_name="A_3_dataset_2_mnist_n65536_c1000.npy")
loadMatrix = np.load("A_3_dataset_2_mnist_n65536_c1000.npy")
print(loadMatrix[:10,:5])
print(loadMatrix.shape)

build_MNIST_matrixA(mnistData = data, 
                    dimension_n = 65536, 
                    value_c = 100, 
                    file_name = "A_3_dataset_2_mnist_n655536_c100.npy")
loadMatrix2 = np.load("A_3_dataset_2_mnist_n655536_c100.npy")
print(loadMatrix2[:10,:5])
print(loadMatrix2.shape)




KeyboardInterrupt: 

In [7]:
build_MNIST_matrixA(mnistData=data, 
                    dimension_n=4096, 
                    value_c=100,
                    file_name="A_3_dataset_2_mnist_n4096_c100.npy")
loadMatrix = np.load("A_3_dataset_2_mnist_n4096_c100.npy")
print(loadMatrix[:10,:5])
print(loadMatrix.shape)

build_MNIST_matrixA(mnistData = data, 
                    dimension_n = 4096, 
                    value_c = 10, 
                    file_name = "A_3_dataset_2_mnist_n4096_c10.npy")
loadMatrix2 = np.load("A_3_dataset_2_mnist_n4096_c10.npy")
print(loadMatrix2[:10,:5])
print(loadMatrix2.shape)




[[1.         0.99127504 0.98824289 0.99001237 0.98907651]
 [0.99127504 1.         0.98715919 0.98829865 0.98930957]
 [0.98824289 0.98715919 1.         0.9898814  0.98994457]
 [0.99001237 0.98829865 0.9898814  1.         0.99126262]
 [0.98907651 0.98930957 0.98994457 0.99126262 1.        ]
 [0.98979753 0.98903161 0.98938555 0.99024257 0.99195122]
 [0.99100754 0.98756737 0.98972827 0.991512   0.9925866 ]
 [0.99278471 0.98967594 0.98934556 0.98962114 0.98935745]
 [0.99136177 0.98870132 0.99122707 0.99290202 0.9940263 ]
 [0.98989935 0.98824599 0.99277739 0.99119833 0.99174104]]
(4096, 4096)
[[1.         0.41631015 0.30645728 0.36649001 0.33341767]
 [0.41631015 1.         0.27461183 0.3081913  0.34136674]
 [0.30645728 0.27461183 1.         0.36167314 0.36398875]
 [0.36649001 0.3081913  0.36167314 1.         0.4157891 ]
 [0.33341767 0.34136674 0.36398875 0.4157891  1.        ]
 [0.35862154 0.33190771 0.34399823 0.37511058 0.44568853]
 [0.40522463 0.28620227 0.35612081 0.42638049 0.47516109]


In [9]:
build_MNIST_matrixA(mnistData=data, 
                    dimension_n=2048, 
                    value_c=100,
                    file_name="A_3_dataset_2_mnist_n2048_c100.npy")
loadMatrix = np.load("A_3_dataset_2_mnist_n2048_c100.npy")
print(loadMatrix[:10,:5])
print(loadMatrix.shape)

build_MNIST_matrixA(mnistData = data, 
                    dimension_n = 2048, 
                    value_c = 10, 
                    file_name = "A_3_dataset_2_mnist_n2048_c10.npy")
loadMatrix2 = np.load("A_3_dataset_2_mnist_n2048_c10.npy")
print(loadMatrix2[:10,:5])
print(loadMatrix2.shape)

[[1.         0.99127504 0.98824289 0.99001237 0.98907651]
 [0.99127504 1.         0.98715919 0.98829865 0.98930957]
 [0.98824289 0.98715919 1.         0.9898814  0.98994457]
 [0.99001237 0.98829865 0.9898814  1.         0.99126262]
 [0.98907651 0.98930957 0.98994457 0.99126262 1.        ]
 [0.98979753 0.98903161 0.98938555 0.99024257 0.99195122]
 [0.99100754 0.98756737 0.98972827 0.991512   0.9925866 ]
 [0.99278471 0.98967594 0.98934556 0.98962114 0.98935745]
 [0.99136177 0.98870132 0.99122707 0.99290202 0.9940263 ]
 [0.98989935 0.98824599 0.99277739 0.99119833 0.99174104]]
(2048, 2048)
[[1.         0.41631015 0.30645728 0.36649001 0.33341767]
 [0.41631015 1.         0.27461183 0.3081913  0.34136674]
 [0.30645728 0.27461183 1.         0.36167314 0.36398875]
 [0.36649001 0.3081913  0.36167314 1.         0.4157891 ]
 [0.33341767 0.34136674 0.36398875 0.4157891  1.        ]
 [0.35862154 0.33190771 0.34399823 0.37511058 0.44568853]
 [0.40522463 0.28620227 0.35612081 0.42638049 0.47516109]


In [ ]:
import numpy as np

n = 2048
R = 5 # R = 5, 10, 20
xi = 10e-1 # signal-to-noise ratio, 10e-1, 10e-2 10e-4

def mnist_Data ():
    # TODO : this function will process mnist data.
    pass 

def polynomial_Decay ():
    # Polynomial Decay.
    p = 0.5 # p = 0.5, 1, 2 
    matrix2 = np.zeros((n, n)) 
    diagonalList = []
    for i in range(R):
        diagonalList.append(1) 
    for i in range(2, n - R + 2):
        diagonalList.append(i ** (- p))
    np.fill_diagonal(matrix2, diagonalList)
    A1 = matrix2
    # print(f"diagonalList is \n{diagonalList}\n")
    print(f"A1 is \n{A1[:5,:5]}\n")
    print(A1.shape)
    np.save("A_1_n2048_polyDecayMatrix.npy", A1)
    print("A_1_n2048_polyDecayMatrix.npy saved successfully.")


def exponential_Decay ():
    # Exponential Decay.
    q = 0.1 # q > 0 controls the rate of exponential decay, q = 0.1,0.25,1
    diagonalList2 = []
    for i in range(R):
        diagonalList2.append(1)
    for i in range(1, n - R + 1):
        diagonalList2.append(10 ** ((-1) * i * q))
    A2 = np.zeros((n, n))
    np.fill_diagonal(A2, diagonalList2)
    # print(f"diagonalList2 is \n{diagonalList2}\n")
    print(f"A2 is \n{A2[:5,:5]}\n")
    print(A2.shape)
    np.save("A_2_n2048_expDecayMatrix.npy", A2)
    print("A_2_n2048_expDecayMatrix.npy saved successfully.")

def check1():
    print("check1()")
    A_1 = np.load("A_1_polyDecayMatrix.npy")
    A_2 = np.load("A_2_expDecayMatrix.npy")
    print(A_1.shape)
    print(A_1)
    print(A_2.shape)
    print(A_2)

if __name__ == "__main__":
    polynomial_Decay()
    exponential_Decay()
    # check1()