In [16]:
from dataset1 import *
import numpy as np
from scipy.linalg import solve_triangular
from numpy.linalg import eigh
import torch
from hadamard_transform import hadamard_transform
import time
import pandas as pd
import seaborn as sns
#test

## Define functions

In [17]:

def getError(A,B):
    return np.linalg.norm(A-B,ord='nuc')/np.linalg.norm(A,ord='nuc')

def fjlt(A, D, indices, direction):
    """
    Applies the Fast Johnson-Lindenstrauss Transform (FJLT) to a square matrix.

    Parameters:
    - A: Input square matrix (NumPy array of size n x m).
    - D: Diagonal vector of +1 and -1 (NumPy array of size n).
    - indices: Indices of the selected rows or columns for subsampling (NumPy array of size l).
    - direction: 'left' to apply FJLT from the left (on rows) or 'right' for the transpose case (on columns).

    Returns:
    - A_proj: Transformed matrix after applying FJLT and subsampling.
    """
    n, m = A.shape
    l = indices.shape[0]  # Sketch size
    if direction == 'left':  # FJLT applied to the rows of A
        assert len(D) == n, "The length of D must match the number of rows in A."
        assert (n & (n - 1) == 0), "The number of rows in A must be a power of 2."
        # Multiply each row of A by the corresponding element in D
        OmegaA = A * D[:, np.newaxis]
        # Apply the Fast Hadamard Transform to the rows
        OmegaA = hadamard_transform(torch.tensor(OmegaA.T)).numpy().T
        # Subsample the rows and scale
        OmegaA = OmegaA[indices, :] * np.sqrt(n / l)
        return np.ascontiguousarray(OmegaA)
    elif direction == 'right':  # FJLT applied to the columns of A
        # Multiply each column of A by the corresponding element in D
        AOmega = A * D[np.newaxis, :]
        # Apply the Fast Hadamard Transform to the columns
        AOmega = hadamard_transform(torch.tensor(AOmega)).numpy()
        # Subsample the columns and scale
        AOmega = AOmega[:, indices] * np.sqrt(n / l)
        return np.ascontiguousarray(AOmega)

def getLowRank(A, rank, sketch_dim, sketch_method='gaussian', good_conditionned=True, print_times=False):
    """
    Compute a low-rank approximation of the matrix A using sketching, 
    eigenvalue decomposition, and truncation. Optionally prints the time taken for each major operation.

    Parameters:
        A (numpy.ndarray): Original matrix (size m x n).
        rank (int): Desired rank for the approximation.
        sketch_dim (int): Dimension of the sketching subspace.
        sketch_method (str): Method used for sketching. Options are:
                             - 'gaussian': Uses a Gaussian random matrix for sketching.
                             - 'fjlt': Uses the Fast Johnson-Lindenstrauss Transform.
        good_conditionned (bool): If True, uses Cholesky decomposition for better conditioning. 
                                  Otherwise, uses eigenvalue decomposition.
        print_times (bool): If True, prints the time taken for each major operation.

    Returns:
        A_nyst_k (numpy.ndarray): Low-rank approximation of A (size m x m).
    """
    m = A.shape[0]
    B = None
    C = None

    start_time = time.time()

    # Apply sketching based on the selected method
    if sketch_method == 'fjlt':  # Use Fast Johnson-Lindenstrauss Transform for sketching
        D = np.random.choice([1, -1], size=m)
        indices = np.random.choice(m, size=sketch_dim, replace=False)
        sketch_start = time.time()
        C = fjlt(A, D, indices, direction='right')
        B = fjlt(C, D, indices, direction='left')
        if print_times:
            print(f"FJLT sketching completed in {time.time() - sketch_start:.6f} seconds.")

    elif sketch_method == 'gaussian':  # Use Gaussian random matrix for sketching
        Omega = np.random.normal(size=(m, sketch_dim))
        sketch_start = time.time()
        C = A @ Omega
        B = Omega.T @ C
        if print_times:
            print(f"Gaussian sketching completed in {time.time() - sketch_start:.6f} seconds.")
    else:
        raise ValueError("Méthode de sketching non reconnue. Choisissez 'gaussian' ou 'fjlt'.")

    if good_conditionned:
        # Use Cholesky decomposition
        cholesky_start = time.time()
        L = np.linalg.cholesky(B)
        if print_times:
            print(f"Cholesky decomposition completed in {time.time() - cholesky_start:.6f} seconds.")
        
        triangular_start = time.time()
        Z = solve_triangular(L, C.T, lower=True).T
        if print_times:
            print(f"Triangular solve completed in {time.time() - triangular_start:.6f} seconds.")
    else:
        # Use eigenvalue decomposition
        eigh_start = time.time()
        eig_v, V = eigh(B)
        if print_times:
            print(f"Eigenvalue decomposition completed in {time.time() - eigh_start:.6f} seconds.")
        
        truncate_start = time.time()
        truncate = eig_v > 0
        eig_v = eig_v[truncate]
        V = V[:, truncate]
        Z = C @ (V * (1 / np.sqrt(eig_v)))
        if print_times:
            print(f"Eigenvalue truncation and normalization completed in {time.time() - truncate_start:.6f} seconds.")

    qr_start = time.time()
    Q, R = np.linalg.qr(Z)
    if print_times:
        print(f"QR decomposition completed in {time.time() - qr_start:.6f} seconds.")

    svd_start = time.time()
    U, Sigma, _ = np.linalg.svd(R)
    if print_times:
        print(f"SVD completed in {time.time() - svd_start:.6f} seconds.")

    approx_start = time.time()
    U_hat = Q @ U[:, :rank]
    A_nyst_k = (U_hat * Sigma[:rank]**2) @ U_hat.T
    if print_times:
        print(f"Low-rank approximation construction completed in {time.time() - approx_start:.6f} seconds.")

    total_time = time.time() - start_time
    if print_times:
        print(f"Total computation time: {total_time:.6f} seconds.")
    error = getError(A,A_nyst_k)
    print(f"Error :{error}".format(error))

    return A_nyst_k, error, 

## Tests

In [20]:
n = 2048
A = getExpMatrix(n,R=10)

In [21]:
getLowRank(A,rank=128,sketch_dim=128,sketch_method='gaussian',good_conditionned=False,print_times=True)

Gaussian sketching completed in 0.022853 seconds.
Eigenvalue decomposition completed in 0.009401 seconds.
Eigenvalue truncation and normalization completed in 0.002759 seconds.
QR decomposition completed in 0.027138 seconds.
SVD completed in 0.005126 seconds.
Low-rank approximation construction completed in 0.032776 seconds.
Total computation time: 0.115525 seconds.
Error :8.329604176432034e-15


(array([[ 1.00000000e+00, -1.16920362e-15,  2.49800181e-16, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.11716192e-15,  1.00000000e+00, -2.77555756e-17, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 2.49800181e-16, -5.55111512e-17,  1.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]),
 8.329604176432034e-15)

In [27]:
getLowRank(A,rank=128,sketch_dim=128,sketch_method='fjlt',good_conditionned=False,print_times=True)

FJLT sketching completed in 0.151482 seconds.
Eigenvalue decomposition completed in 0.007486 seconds.
Eigenvalue truncation and normalization completed in 0.001138 seconds.
QR decomposition completed in 0.031378 seconds.
SVD completed in 0.005304 seconds.
Low-rank approximation construction completed in 0.012530 seconds.
Total computation time: 0.210103 seconds.


KeyboardInterrupt: 

## Section 2

We'll compute the error with respect to three matrices. 
1. polynomial decay (dimension 1000 * 1000) locates: 
2. exp decay locates:
3. ../Dataset/A_3_dataset_2_mnist.npy 
    denotes the matrix obtained from MNIST, with c=100
4. 

In [23]:
# Loading matrices

loadMatrix_A_3 = np.load("../Dataset/A_3_dataset_2_mnist.npy")
print("matrix A_3")
print(loadMatrix_A_3.shape)
print(loadMatrix_A_3[:10,:5])

loadMatrix_A_1 = np.load("../Dataset/A_1_polyDecayMatrix.npy")
loadMatrix_A_2 = np.load("../Dataset/A_2_expDecayMatrix.npy")

print("matrix A_1")
print(loadMatrix_A_1.shape)
print(loadMatrix_A_1[:10,:5])

print("matrix A_2")
print(loadMatrix_A_2.shape)
print(loadMatrix_A_2[:10,:5])

matrix A_3
(1000, 1000)
[[1.         0.99127504 0.98824289 0.99001237 0.98907651]
 [0.99127504 1.         0.98715919 0.98829865 0.98930957]
 [0.98824289 0.98715919 1.         0.9898814  0.98994457]
 [0.99001237 0.98829865 0.9898814  1.         0.99126262]
 [0.98907651 0.98930957 0.98994457 0.99126262 1.        ]
 [0.98979753 0.98903161 0.98938555 0.99024257 0.99195122]
 [0.99100754 0.98756737 0.98972827 0.991512   0.9925866 ]
 [0.99278471 0.98967594 0.98934556 0.98962114 0.98935745]
 [0.99136177 0.98870132 0.99122707 0.99290202 0.9940263 ]
 [0.98989935 0.98824599 0.99277739 0.99119833 0.99174104]]
matrix A_1
(1000, 1000)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
matrix A_2
(1000, 1000)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0.

In [24]:
from tqdm import tqdm  # For progress tracking

def collect_low_rank_errors(A, max_rank=128, sketch_dims=range(10, 101, 10), is_good_conditionned=False, sketch_method='gaussian', output_file='Section_2_test_1_for_loadMatrixA_1.xlsx'):
    """
    Computes errors for various ranks and sketch dimensions using the `getLowRank` function.

    Parameters:
    - A (np.ndarray): Input matrix of size, for example 1000x1000.
    - max_rank (int): Maximum rank to test (0 <= rank <= max_rank).
    - sketch_dims (iterable): Values of sketch dimensions to test.
    - sketch_method (str): Method for sketching ('gaussian' or other supported by `getLowRank`).
    - output_file (str): Path to the file where results are saved (.csv or .xlsx).
    
    Saves:
    - A table with columns: "Approximation Rank", "Sketch Dimension", "Error Value",
      clearly labeled for reuse and analysis.
    """
    # Ensure the matrix is square and 1000x1000
    # assert A.shape == (1000, 1000), "Matrix A must be of size 1000x1000."
    
    # Prepare a list to store results
    results = []
    
    # Iterate through all rank and sketch_dim combinations
    for rank in tqdm(range(max_rank + 1), desc="Ranks Progress", unit="rank"):
        for sketch_dim in sketch_dims:
            # Compute the error
            error = getLowRank(A, rank, sketch_dim, sketch_method, good_conditionned = is_good_conditionned)
            # Append results with clear column names
            results.append({
                'Approximation Rank': rank,
                'Sketch Dimension': sketch_dim,
                'Error Value': error,
                'Sketch Method': sketch_method  # Added for better traceability
            })
    
    # Convert to DataFrame for easy export
    df = pd.DataFrame(results)
    
    # Save results to a human-readable format
    if output_file.endswith('.csv'):
        df.to_csv(output_file, index=False)
    elif output_file.endswith('.xlsx'):
        df.to_excel(output_file, index=False, engine='openpyxl')
    else:
        raise ValueError("Output file must be either .csv or .xlsx")
    
    print(f"Results successfully saved to {output_file}.")


In [25]:
collect_low_rank_errors(loadMatrix_A_1)

Ranks Progress:   0%|          | 0/129 [00:00<?, ?rank/s]

Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0


Ranks Progress:   1%|          | 1/129 [00:05<12:02,  5.65s/rank]

Error :1.0
Error :0.9482924928005755
Error :0.9457201976509276
Error :0.9437538416677704
Error :0.9425313559274502
Error :0.9415654469594548
Error :0.9413661874204159
Error :0.9413237319266492
Error :0.9407889385174028
Error :0.9407501496845445


Ranks Progress:   2%|▏         | 2/129 [00:11<12:26,  5.88s/rank]

Error :0.940747567608469
Error :0.9000185099599731
Error :0.8914132367880379
Error :0.8888296537127424
Error :0.8853092326829771
Error :0.8838649729802387
Error :0.8836483471735554
Error :0.8820558880384127
Error :0.8822410316145832
Error :0.8815910433986858


Ranks Progress:   2%|▏         | 3/129 [00:18<12:58,  6.18s/rank]

Error :0.8812719296452977
Error :0.849701164947869
Error :0.8379359666409442
Error :0.8334248653340183
Error :0.8313232870076201
Error :0.826507053468152
Error :0.8249655158534179
Error :0.8236542772753546
Error :0.8229707083804705
Error :0.8229803884092001


Ranks Progress:   3%|▎         | 4/129 [00:24<13:06,  6.29s/rank]

Error :0.821799267362474
Error :0.8054177453737966
Error :0.7807465675486714
Error :0.7772465411321061
Error :0.7768609991888852
Error :0.7705697052704572
Error :0.7678179712517698
Error :0.766470977497621
Error :0.7662946881328137
Error :0.7635568517408639


Ranks Progress:   4%|▍         | 5/129 [00:31<13:02,  6.31s/rank]

Error :0.7629428836250178
Error :0.7709225461217527
Error :0.7491500221778729
Error :0.7244668252054681
Error :0.7190164190622677
Error :0.7127896685728657
Error :0.7107195174095658
Error :0.7079749458466176
Error :0.707048617340896
Error :0.7061767458387739


Ranks Progress:   5%|▍         | 6/129 [00:37<12:56,  6.31s/rank]

Error :0.704092707779969
Error :0.7428106446798443
Error :0.6996880879930725
Error :0.6787524735400455
Error :0.6675597547232498
Error :0.6616765229643106
Error :0.6549395777679775
Error :0.6513649102677072
Error :0.6495675862472546
Error :0.647997206187673


Ranks Progress:   5%|▌         | 7/129 [00:43<12:48,  6.30s/rank]

Error :0.6459212730503493
Error :0.7254031783459535
Error :0.6491317892990436
Error :0.6282604579840634
Error :0.610497805140912
Error :0.6082768635750454
Error :0.6004174631459945
Error :0.5955957721921901
Error :0.5917241821774774
Error :0.5881841689589146


Ranks Progress:   6%|▌         | 8/129 [00:49<12:43,  6.31s/rank]

Error :0.5893586999540084
Error :0.7301600619806893
Error :0.6242955483493993
Error :0.5739309548416384
Error :0.5653474919776514
Error :0.5525379919868776
Error :0.5449504583253222
Error :0.5378870682989175
Error :0.5380684418359037
Error :0.5330786990644711


Ranks Progress:   7%|▋         | 9/129 [00:55<12:26,  6.22s/rank]

Error :0.5305027527240214
Error :0.6797382346810183
Error :0.5771452327596575
Error :0.5418441522999501
Error :0.5147660935182466
Error :0.4995919022325686
Error :0.4913042429272825
Error :0.48345721208474424
Error :0.4816447434982344
Error :0.47646408210098584


Ranks Progress:   8%|▊         | 10/129 [01:02<12:35,  6.35s/rank]

Error :0.47362017087345104
Error :0.6688225370411875
Error :0.5633415378740605
Error :0.5203944528475013
Error :0.46235142903206916
Error :0.45610840753860843
Error :0.43953215489846464
Error :0.4306160788049229
Error :0.4257690235558425
Error :0.4170384192138286


Ranks Progress:   9%|▊         | 11/129 [01:09<12:34,  6.39s/rank]

Error :0.4143961441495682
Error :0.7112251775551721
Error :0.5609004652940685
Error :0.4775036975172316
Error :0.43779627604289817
Error :0.42287914731375886
Error :0.41098649655561675
Error :0.40473289425541714
Error :0.39901414348273423
Error :0.3903699320836682


Ranks Progress:   9%|▉         | 12/129 [01:15<12:26,  6.38s/rank]

Error :0.3868460742039404
Error :0.7034469124804721
Error :0.5454541964971781
Error :0.4661289383738139
Error :0.4407866898379854
Error :0.4163652293204743
Error :0.3908377995451396
Error :0.384956514646443
Error :0.3774749334844809
Error :0.37311062733111544


Ranks Progress:  10%|█         | 13/129 [01:21<12:11,  6.31s/rank]

Error :0.37128493909992366
Error :0.6796888250207831
Error :0.5219514288816293
Error :0.45574249291588725
Error :0.42722638067729896
Error :0.397698253137712
Error :0.3887871758964743
Error :0.38016730562294726
Error :0.3650307688231141
Error :0.36335835977621467


Ranks Progress:  11%|█         | 14/129 [01:28<12:16,  6.41s/rank]

Error :0.3573915114899796
Error :0.7038534646057776
Error :0.5432810627272328
Error :0.46159970371001524
Error :0.4218339247522293
Error :0.385405691402828
Error :0.37992808385743443
Error :0.3690878625473967
Error :0.36100870624046993
Error :0.3503451517880338


Ranks Progress:  12%|█▏        | 15/129 [01:34<12:00,  6.32s/rank]

Error :0.34586765367382116
Error :0.6999801649326496
Error :0.5392416857457689
Error :0.4635503127467832
Error :0.4058807676614427
Error :0.3864428397342357
Error :0.37015527251104124
Error :0.3581462388253183
Error :0.3504302907579749
Error :0.3435887662558841


Ranks Progress:  12%|█▏        | 16/129 [01:41<12:12,  6.48s/rank]

Error :0.3420440727441254
Error :0.6978408996037094
Error :0.5570747839488365
Error :0.4292022633069794
Error :0.40487459173441087
Error :0.3789739761889653
Error :0.3660998660102845
Error :0.35298342870840943
Error :0.34911800365235224
Error :0.3355182698680091


Ranks Progress:  13%|█▎        | 17/129 [01:47<11:55,  6.39s/rank]

Error :0.3308471756122297
Error :0.7148530918993506
Error :0.5023960386148291
Error :0.4432118317972395
Error :0.4093433445919331
Error :0.38557551081236874
Error :0.3623700184928516
Error :0.34939351831893195
Error :0.33987194821907135
Error :0.32650405543942096


Ranks Progress:  14%|█▍        | 18/129 [01:53<11:49,  6.39s/rank]

Error :0.32540411970990984
Error :0.6945011018029345
Error :0.5360717388153341
Error :0.4356023039094818
Error :0.39834744787366994
Error :0.3875080236543909
Error :0.3578303412752143
Error :0.33936040783555543
Error :0.32882166841585786
Error :0.33080924128958417


Ranks Progress:  15%|█▍        | 19/129 [02:00<11:46,  6.42s/rank]

Error :0.32208033065086267
Error :0.6906380755721259
Error :0.512892219194574
Error :0.46156756056731496
Error :0.3979450008658368
Error :0.37767667227505314
Error :0.35164495518913513
Error :0.33367133574987673
Error :0.3256340287269839
Error :0.3193723154160644


Ranks Progress:  16%|█▌        | 20/129 [02:06<11:39,  6.41s/rank]

Error :0.31588503909365107
Error :0.6941218019529097
Error :0.4952811587133367
Error :0.4465960407197368
Error :0.3974720514916263
Error :0.3691287538520199
Error :0.34405070692107037
Error :0.3387174331468657
Error :0.3273179075575684
Error :0.31842539492007604


Ranks Progress:  16%|█▋        | 21/129 [02:13<11:33,  6.43s/rank]

Error :0.3169300101835261
Error :0.6802955319832376
Error :0.514771229267868
Error :0.44923608661259934
Error :0.39754856104784747
Error :0.36370411046659523
Error :0.34097869189473046
Error :0.3323305282506462
Error :0.3213170407208016
Error :0.3155828507604227


Ranks Progress:  17%|█▋        | 22/129 [02:19<11:20,  6.36s/rank]

Error :0.3094010929400023
Error :0.6899508620765299
Error :0.5173431167380009
Error :0.4411096085917749
Error :0.3851657019285886
Error :0.3610362594903189
Error :0.34787451466530056
Error :0.3308893886814676
Error :0.31683101033606414
Error :0.31157404908818925


Ranks Progress:  18%|█▊        | 23/129 [02:25<11:10,  6.32s/rank]

Error :0.30365862490553847
Error :0.6870619793532825
Error :0.5296980345546175
Error :0.44370689164399774
Error :0.39589657049576554
Error :0.37370688083198994
Error :0.3421375341107363
Error :0.3217936513125651
Error :0.3200399283970851
Error :0.3103677729454643


Ranks Progress:  19%|█▊        | 24/129 [02:31<11:03,  6.32s/rank]

Error :0.3022608205114225
Error :0.729550444784386
Error :0.5392848661244515
Error :0.44340809856016067
Error :0.39979468606846125
Error :0.3576022187271587
Error :0.34034516863700737
Error :0.32524880213107893
Error :0.31190741490744034
Error :0.3084175101721058


Ranks Progress:  19%|█▉        | 25/129 [02:38<10:56,  6.32s/rank]

Error :0.29992864375947403
Error :0.6843207204843603
Error :0.5340992658530385
Error :0.421934756137536
Error :0.3865578126126074
Error :0.359746294825671
Error :0.340054407441971
Error :0.32154934014358005
Error :0.31591053043041895
Error :0.3075622029674041


Ranks Progress:  20%|██        | 26/129 [02:44<10:48,  6.29s/rank]

Error :0.2980573295697485
Error :0.6768441116622559
Error :0.5208739044934427
Error :0.4352216571034251
Error :0.3885422542362256
Error :0.3639231400797144
Error :0.3411885105786422
Error :0.3221157285093208
Error :0.30518967073843584
Error :0.29980678174948866


Ranks Progress:  21%|██        | 27/129 [02:50<10:35,  6.23s/rank]

Error :0.2958058022355673
Error :0.6742894589385126
Error :0.5370019243155923
Error :0.41118415224529975
Error :0.37336052309560563
Error :0.3548160365271388
Error :0.326178134377863
Error :0.3171823392328599
Error :0.31170004128907036
Error :0.3004908306380352


Ranks Progress:  22%|██▏       | 28/129 [02:57<10:42,  6.36s/rank]

Error :0.2941189516774137
Error :0.6805772506016318
Error :0.5064198478490365
Error :0.43575020570974493
Error :0.38457011021592674
Error :0.3490846267507721
Error :0.3314449565143137
Error :0.3181337878269632
Error :0.3053179117853757
Error :0.2997703566967461


Ranks Progress:  22%|██▏       | 29/129 [03:03<10:33,  6.33s/rank]

Error :0.29184478313551615
Error :0.6930867509461243
Error :0.5246498489600079
Error :0.4403807428525576
Error :0.3838019329654286
Error :0.35281309829565677
Error :0.33974048217563774
Error :0.3165115082968514
Error :0.30211200689766954
Error :0.2957156089133893


Ranks Progress:  23%|██▎       | 30/129 [03:09<10:31,  6.37s/rank]

Error :0.2896216648220028
Error :0.6846492275582028
Error :0.5178979804770188
Error :0.43520202084694315
Error :0.38748984683464605
Error :0.34937669417887013
Error :0.32645670603018395
Error :0.3169929153322394
Error :0.30423278824363603
Error :0.2931428688832201


Ranks Progress:  24%|██▍       | 31/129 [03:16<10:25,  6.38s/rank]

Error :0.2864313180059055
Error :0.7059190695894876
Error :0.5260307175268719
Error :0.42185792515610354
Error :0.3785854750079772
Error :0.3492855657460756
Error :0.32826465399299726
Error :0.30595777277290825
Error :0.30453782167323856
Error :0.2930166301990956


Ranks Progress:  25%|██▍       | 32/129 [03:22<10:13,  6.32s/rank]

Error :0.28484572365610866
Error :0.6971467354120547
Error :0.5187723318682326
Error :0.4422136429708853
Error :0.37732638836569393
Error :0.34521110756415246
Error :0.333091998086471
Error :0.308616226578285
Error :0.3012806101695925
Error :0.28828760550194665


Ranks Progress:  26%|██▌       | 33/129 [03:29<10:23,  6.50s/rank]

Error :0.28665917929464435
Error :0.6805856558149885
Error :0.5418547792955888
Error :0.41517602910656415
Error :0.3685703787715314
Error :0.3495629937938784
Error :0.32791689560026027
Error :0.312484465544955
Error :0.29988101795068695
Error :0.2900462097698965


Ranks Progress:  26%|██▋       | 34/129 [03:35<10:15,  6.48s/rank]

Error :0.28258172378353363
Error :0.665091132730661
Error :0.5298645432209496
Error :0.43456357023409137
Error :0.3846990494117652
Error :0.3474828022359422
Error :0.3287820971915124
Error :0.31010540570218764
Error :0.2975000925233413
Error :0.2900700992856642


Ranks Progress:  27%|██▋       | 35/129 [03:42<10:06,  6.45s/rank]

Error :0.28206014964888376
Error :0.695083573687129
Error :0.4949988975215034
Error :0.42505250388211346
Error :0.3789125306397358
Error :0.33719178769672203
Error :0.32061046276876526
Error :0.30946460537831466
Error :0.2969482844043295
Error :0.2865396249744025


Ranks Progress:  28%|██▊       | 36/129 [03:48<10:00,  6.46s/rank]

Error :0.27854953241046104
Error :0.696211236208249
Error :0.5054964185934651
Error :0.4375013509751482
Error :0.3742761188618333
Error :0.34733076492644943
Error :0.3254597450494137
Error :0.3067025700666911
Error :0.2957691375530343
Error :0.28884432823197687


Ranks Progress:  29%|██▊       | 37/129 [03:55<09:52,  6.44s/rank]

Error :0.2763619777182023
Error :0.6995923615439068
Error :0.5259814932212579
Error :0.4262756938881024
Error :0.3812380636865108
Error :0.34566775283369156
Error :0.3234515560691266
Error :0.30328520556883
Error :0.29654903328759596
Error :0.28432967698450273


Ranks Progress:  29%|██▉       | 38/129 [04:01<09:40,  6.38s/rank]

Error :0.27847582966435036
Error :0.7232122503808072
Error :0.528330300866842
Error :0.43393821346751915
Error :0.38900529534933825
Error :0.34487975475036325
Error :0.3171165800144956
Error :0.3040108524705662
Error :0.29568960126721555
Error :0.28329569196327736


Ranks Progress:  30%|███       | 39/129 [04:07<09:35,  6.39s/rank]

Error :0.27617085179969575
Error :0.6943282450894818
Error :0.5117058225158908
Error :0.4423832933980927
Error :0.3738322895420735
Error :0.3457164312563204
Error :0.319027628031074
Error :0.3039818163150579
Error :0.29352056520584385
Error :0.2808861366425489


Ranks Progress:  31%|███       | 40/129 [04:14<09:32,  6.43s/rank]

Error :0.2747137629420812
Error :0.6974215798120631
Error :0.5305156448322385
Error :0.4313594082763592
Error :0.374544217883802
Error :0.34572936083571865
Error :0.31803460023589575
Error :0.30033682888794766
Error :0.2888827009508694
Error :0.28254459374377927


Ranks Progress:  32%|███▏      | 41/129 [04:20<09:27,  6.45s/rank]

Error :0.27612426256151346
Error :0.6936410034061418
Error :0.5252935910738824
Error :0.43856827517600544
Error :0.36546378206313274
Error :0.33631543978698214
Error :0.31692111879896573
Error :0.30369388863626245
Error :0.29302951542211675
Error :0.2813579359131478


Ranks Progress:  33%|███▎      | 42/129 [04:26<09:04,  6.26s/rank]

Error :0.271808149285318
Error :0.6936661803250495
Error :0.5271169146054293
Error :0.4187301895972731
Error :0.38539982968766984
Error :0.33603290571304073
Error :0.316245890857858
Error :0.30695268734538733
Error :0.2916301872241183
Error :0.28052945694453096


Ranks Progress:  33%|███▎      | 43/129 [04:32<08:58,  6.26s/rank]

Error :0.27084437451133536
Error :0.7079819481521927
Error :0.5241792745212913
Error :0.4123198552595431
Error :0.39722246024004476
Error :0.3440138462019515
Error :0.3182765323995248
Error :0.297876300494312
Error :0.2902144794136748
Error :0.2796791351236626


Ranks Progress:  34%|███▍      | 44/129 [04:39<09:05,  6.42s/rank]

Error :0.2704335216642227
Error :0.7034544423910379
Error :0.528508888520405
Error :0.4394012572189883
Error :0.37170498418707076
Error :0.34221680167552293
Error :0.3244543377094682
Error :0.2981043816776055
Error :0.28751203993846314
Error :0.2771161599422879


Ranks Progress:  35%|███▍      | 45/129 [04:46<08:58,  6.42s/rank]

Error :0.2712990062100839
Error :0.6788556730179096
Error :0.5290595595806877
Error :0.44049022641579605
Error :0.3743882978432387
Error :0.34784261408465483
Error :0.3196796954786569
Error :0.30309201006462705
Error :0.288281280710041
Error :0.2772749631651267


Ranks Progress:  36%|███▌      | 46/129 [04:52<08:54,  6.44s/rank]

Error :0.2695950516758921
Error :0.7041223796458368
Error :0.5283721168217589
Error :0.43514549958060744
Error :0.38623748697022636
Error :0.33028667593058586
Error :0.3178582076840883
Error :0.29412014991994384
Error :0.28759099726882376
Error :0.2736560270604978


Ranks Progress:  36%|███▋      | 47/129 [04:59<08:50,  6.47s/rank]

Error :0.26988911144832756
Error :0.6907614863591263
Error :0.5240656307164416
Error :0.42446723120228386
Error :0.37357393865018224
Error :0.34104927604049423
Error :0.31491659817226725
Error :0.2974926464496136
Error :0.2843951595465369
Error :0.27558791592292176


Ranks Progress:  37%|███▋      | 48/129 [05:05<08:36,  6.38s/rank]

Error :0.2658895105190571
Error :0.6909611821313049
Error :0.5310954565599563
Error :0.443906353521393
Error :0.3719664864269591
Error :0.3362093377639191
Error :0.31337463040417424
Error :0.2954207066577744
Error :0.28852046178793483
Error :0.2765595867604868


Ranks Progress:  38%|███▊      | 49/129 [05:12<08:46,  6.58s/rank]

Error :0.2690092998022299
Error :0.6781904316609024
Error :0.5277724923199938
Error :0.4523896793328814
Error :0.37842847180936073
Error :0.3427066608200615
Error :0.31601365239256746
Error :0.29656836317881347
Error :0.2861009625383393
Error :0.27247725462597555


Ranks Progress:  39%|███▉      | 50/129 [05:18<08:35,  6.52s/rank]

Error :0.2679906184285314
Error :0.6853969846224068
Error :0.5142257475260751
Error :0.4250879315553444
Error :0.3829974251394308
Error :0.34065455413779583
Error :0.3191509101294057
Error :0.29522256444572087
Error :0.2849982835864182
Error :0.27256495144612397


Ranks Progress:  40%|███▉      | 51/129 [05:25<08:25,  6.49s/rank]

Error :0.26344469640117624
Error :0.7498201747619212
Error :0.5232580365265432
Error :0.43930524828456224
Error :0.38470348607149035
Error :0.3318526857082881
Error :0.31396717524396
Error :0.2971094892503662
Error :0.2866411031481808
Error :0.2718241752998936


Ranks Progress:  40%|████      | 52/129 [05:32<08:36,  6.71s/rank]

Error :0.263076894665429
Error :0.6883082412356499
Error :0.5346327047825175
Error :0.42729087150151934
Error :0.37041766821775013
Error :0.3398353979345737
Error :0.3135294383661973
Error :0.2974579512555748
Error :0.2847171860098016
Error :0.2720287314988358


Ranks Progress:  41%|████      | 53/129 [05:38<08:22,  6.62s/rank]

Error :0.265183891096632
Error :0.6767329108754262
Error :0.5173977620893722
Error :0.4437847312767909
Error :0.3819322966840326
Error :0.34196971318926145
Error :0.3179510256730411
Error :0.2948870926832273
Error :0.28561591983124446
Error :0.27276070972465405


Ranks Progress:  42%|████▏     | 54/129 [05:45<08:13,  6.58s/rank]

Error :0.2652600751014036
Error :0.7004885812407503
Error :0.5108536077269795
Error :0.4315317625500838
Error :0.38370432613274796
Error :0.33505519618408014
Error :0.31747193779994937
Error :0.297449713895822
Error :0.2814084904533131
Error :0.2705212616534399


Ranks Progress:  43%|████▎     | 55/129 [05:51<08:01,  6.51s/rank]

Error :0.2645100277569878
Error :0.6838942907233616
Error :0.5388190982148735
Error :0.43804618084437036
Error :0.37329142364548373
Error :0.3355450269958387
Error :0.31150368924018607
Error :0.29511183230307725
Error :0.28200548797180136
Error :0.27192347534928285


Ranks Progress:  43%|████▎     | 56/129 [05:57<07:53,  6.48s/rank]

Error :0.2613999770080305
Error :0.6984821447536405
Error :0.5215729045960171
Error :0.4295304375742781
Error :0.37691732797250577
Error :0.34261215482642465
Error :0.3145005760408913
Error :0.2915286361907346
Error :0.2787966278433613
Error :0.2704739625366229


Ranks Progress:  44%|████▍     | 57/129 [06:04<07:46,  6.48s/rank]

Error :0.26158207592125604
Error :0.7116703784533706
Error :0.5061043075094387
Error :0.4214901216772049
Error :0.3622763706440038
Error :0.33672431548570947
Error :0.31886908405197767
Error :0.2894006356805698
Error :0.28358313490548676
Error :0.2689849877344677


Ranks Progress:  45%|████▍     | 58/129 [06:10<07:37,  6.45s/rank]

Error :0.2660073998119609
Error :0.672589231734272
Error :0.528914593907517
Error :0.4484536558957933
Error :0.3844928333088113
Error :0.3394031836458725
Error :0.30906164862116325
Error :0.2974115370758462
Error :0.2799857822252618
Error :0.2742959848990034


Ranks Progress:  46%|████▌     | 59/129 [06:17<07:33,  6.48s/rank]

Error :0.2614324040564188
Error :0.6944100849683054
Error :0.5347742844820136
Error :0.4252133386995723
Error :0.3763156637051067
Error :0.3397535370170397
Error :0.3119594510205768
Error :0.29110427728073063
Error :0.2802139603991513
Error :0.2685453053130919


Ranks Progress:  47%|████▋     | 60/129 [06:23<07:25,  6.46s/rank]

Error :0.26092900103367783
Error :0.6914156583773381
Error :0.5137795757559193
Error :0.4349284733901351
Error :0.37498266994274104
Error :0.3342272265317575
Error :0.31128628948278525
Error :0.29033951684447906
Error :0.27660714006021775
Error :0.2681404318523149


Ranks Progress:  47%|████▋     | 61/129 [06:30<07:15,  6.40s/rank]

Error :0.2595839597727165
Error :0.6759169572709601
Error :0.5323055356413773
Error :0.4381915466810044
Error :0.37406561509744135
Error :0.33331403421632044
Error :0.3116052145467724
Error :0.29075914642715306
Error :0.2824676037212165
Error :0.26721924498923283


Ranks Progress:  48%|████▊     | 62/129 [06:36<07:07,  6.38s/rank]

Error :0.2624034248576341
Error :0.6802557740511525
Error :0.5194359372559579
Error :0.4382138140265187
Error :0.3756805515810752
Error :0.33169431147058526
Error :0.31552777572098767
Error :0.29535166148623093
Error :0.27755784033527486
Error :0.27140742358091496


Ranks Progress:  49%|████▉     | 63/129 [06:42<07:00,  6.37s/rank]

Error :0.2593063749421103
Error :0.6877379494509623
Error :0.5176965495710124
Error :0.45220270894327935
Error :0.3658126931720909
Error :0.33616096466499673
Error :0.30997337671082487
Error :0.29564746377172424
Error :0.27924563593439367
Error :0.2691892971806094


Ranks Progress:  50%|████▉     | 64/129 [06:49<06:56,  6.41s/rank]

Error :0.2609928437142795
Error :0.7082497791218165
Error :0.5396850744864035
Error :0.43400911760699984
Error :0.38368679730429583
Error :0.3345642994143677
Error :0.3081133058332249
Error :0.2873009427430725
Error :0.2821806341759499
Error :0.2688483722105178


Ranks Progress:  50%|█████     | 65/129 [06:55<06:50,  6.41s/rank]

Error :0.25662389470002017
Error :0.6807346826020252
Error :0.5202777485022277
Error :0.43527475968467827
Error :0.37589427274518356
Error :0.34022506318655205
Error :0.3087177404859407
Error :0.290967035106155
Error :0.27541670023911247
Error :0.26505925326210306


Ranks Progress:  51%|█████     | 66/129 [07:02<06:43,  6.40s/rank]

Error :0.2570895625969961
Error :0.685594896342191
Error :0.5173492186250755
Error :0.434747769332342
Error :0.37707679145275647
Error :0.3324318576134215
Error :0.3109663554027241
Error :0.28842562130675314
Error :0.27815453857235084
Error :0.26231633212588634


Ranks Progress:  52%|█████▏    | 67/129 [07:08<06:36,  6.40s/rank]

Error :0.25576523261124673
Error :0.6893346007916014
Error :0.5174187505297316
Error :0.4381982740946608
Error :0.3705198325317279
Error :0.34364879504459056
Error :0.3154146503412462
Error :0.2894991521209673
Error :0.2776471200973273
Error :0.2638777460170179


Ranks Progress:  53%|█████▎    | 68/129 [07:14<06:31,  6.41s/rank]

Error :0.25456417534625775
Error :0.6902286668500134
Error :0.5060350528007084
Error :0.4479687288202732
Error :0.37773315563427173
Error :0.3396642369212533
Error :0.32087462412362067
Error :0.29416556295781565
Error :0.2779997011818776
Error :0.26777506708786636


Ranks Progress:  53%|█████▎    | 69/129 [07:21<06:25,  6.42s/rank]

Error :0.25623547397318597
Error :0.6896126670612809
Error :0.5183911372917179
Error :0.43557154131816467
Error :0.38844057545374794
Error :0.33599756395407104
Error :0.3143683284987448
Error :0.29241208841122796
Error :0.27890497062466285
Error :0.2631247721777026


Ranks Progress:  54%|█████▍    | 70/129 [07:27<06:17,  6.40s/rank]

Error :0.26231615436663447
Error :0.6860381440056547
Error :0.5132399967177717
Error :0.446605571177628
Error :0.3646275326610614
Error :0.33731458405178194
Error :0.3060939818912392
Error :0.28363775467522884
Error :0.2769836043093551
Error :0.2676550998573967


Ranks Progress:  55%|█████▌    | 71/129 [07:34<06:11,  6.41s/rank]

Error :0.2566060881803559
Error :0.6965846132174809
Error :0.51732161225235
Error :0.42701407449048046
Error :0.37618224884279
Error :0.33184723979887276
Error :0.30509781006966047
Error :0.2939987274392112
Error :0.27865178920656386
Error :0.2643574449229252


Ranks Progress:  56%|█████▌    | 72/129 [07:40<06:06,  6.44s/rank]

Error :0.25377721566588235
Error :0.6916137265474435
Error :0.5212662411613231
Error :0.43735168126102786
Error :0.3688290751810664
Error :0.3343314224031447
Error :0.3125839203523556
Error :0.29125103026353644
Error :0.27123127264952507
Error :0.2622101146335575


Ranks Progress:  57%|█████▋    | 73/129 [07:47<06:00,  6.44s/rank]

Error :0.25506946898813276
Error :0.6948773285760159
Error :0.5134318573843435
Error :0.42481959784448037
Error :0.38149336722137045
Error :0.3479721119914851
Error :0.3137087075103523
Error :0.2893352350838414
Error :0.2765167812273372
Error :0.26346172615828484


Ranks Progress:  57%|█████▋    | 74/129 [07:53<05:54,  6.45s/rank]

Error :0.2568122088875643
Error :0.6845389450180146
Error :0.5303956418898333
Error :0.42366483455988274
Error :0.3745165962998502
Error :0.3469573927710503
Error :0.3198198997089938
Error :0.2922344739858317
Error :0.2751198478656966
Error :0.2630146424690208


Ranks Progress:  58%|█████▊    | 75/129 [08:00<05:50,  6.49s/rank]

Error :0.2535159476177211
Error :0.6591150213538179
Error :0.5003136858935009
Error :0.4367384882831563
Error :0.3709237671210188
Error :0.3387584895584986
Error :0.31746635406006496
Error :0.2923592108024218
Error :0.2735921625770626
Error :0.26133306766628916


Ranks Progress:  59%|█████▉    | 76/129 [08:06<05:46,  6.54s/rank]

Error :0.25228838620099964
Error :0.6751423463666582
Error :0.5318428337364813
Error :0.4408428411623448
Error :0.37458504444811697
Error :0.3373247984161338
Error :0.3116370861824859
Error :0.29261223951005677
Error :0.27465510253090125
Error :0.2612234586899267


Ranks Progress:  60%|█████▉    | 77/129 [08:13<05:39,  6.53s/rank]

Error :0.25158948229276346
Error :0.7055208318122673
Error :0.5199644908871477
Error :0.4200234333003965
Error :0.3718928550500009
Error :0.33888607072120674
Error :0.30822747226693503
Error :0.28738465611062236
Error :0.2757837539867263
Error :0.25936355274318756


Ranks Progress:  60%|██████    | 78/129 [08:19<05:31,  6.51s/rank]

Error :0.25181441824277695
Error :0.7081718218145487
Error :0.5186775276655042
Error :0.42416629286671703
Error :0.35719090096077344
Error :0.3345561246138613
Error :0.3206200903227073
Error :0.28168730333612335
Error :0.2772659339434379
Error :0.26462949843659134


Ranks Progress:  61%|██████    | 79/129 [08:26<05:25,  6.50s/rank]

Error :0.25063326969972344
Error :0.7040177009378599
Error :0.5392590670260947
Error :0.43076576435335556
Error :0.37511036403922754
Error :0.3402081181149699
Error :0.312774891495522
Error :0.28597028941874525
Error :0.27044774666925503
Error :0.2600059908748801


Ranks Progress:  62%|██████▏   | 80/129 [08:32<05:16,  6.45s/rank]

Error :0.25273735512144857
Error :0.6951195162251301
Error :0.5458972093643011
Error :0.4229823683633764
Error :0.3671739388486047
Error :0.3484424318931732
Error :0.31085573303990693
Error :0.29381238462095655
Error :0.27523155892501355
Error :0.25960335355675457


Ranks Progress:  63%|██████▎   | 81/129 [08:38<05:07,  6.42s/rank]

Error :0.2525193614638146
Error :0.7106692948164388
Error :0.5595772171230833
Error :0.42940590363838343
Error :0.3706695721325031
Error :0.33219012373221296
Error :0.3067146027025134
Error :0.29046781488671236
Error :0.27716119340877593
Error :0.26042064471549337


Ranks Progress:  64%|██████▎   | 82/129 [08:45<05:03,  6.45s/rank]

Error :0.2568854357098403
Error :0.6594544247929524
Error :0.5282766638220228
Error :0.4353586783397547
Error :0.37953121578213883
Error :0.34540300049675426
Error :0.3175363649943539
Error :0.29261642931651466
Error :0.271615341121671
Error :0.2634490359693032


Ranks Progress:  64%|██████▍   | 83/129 [08:51<04:56,  6.44s/rank]

Error :0.2531631806579159
Error :0.683795530222832
Error :0.5432522621078918
Error :0.44165077873021774
Error :0.3732771963757461
Error :0.3390388861965329
Error :0.3087070650343228
Error :0.29333289258112777
Error :0.2765124775264659
Error :0.25940310531992355


Ranks Progress:  65%|██████▌   | 84/129 [08:58<04:54,  6.54s/rank]

Error :0.24771052941681662
Error :0.6761636233785073
Error :0.5278394746050109
Error :0.4131921547346709
Error :0.38949991022106917
Error :0.3434094611840298
Error :0.3073359023521174
Error :0.29334908169848384
Error :0.2797219741022552
Error :0.26144679500539586


Ranks Progress:  66%|██████▌   | 85/129 [09:05<04:46,  6.50s/rank]

Error :0.25025568232696893
Error :0.6967321391374709
Error :0.5144904381095539
Error :0.43032794168500155
Error :0.38532207546092423
Error :0.3406538217653584
Error :0.3176690828598812
Error :0.29192620259433755
Error :0.27367701805259387
Error :0.2559021894940836


Ranks Progress:  67%|██████▋   | 86/129 [09:11<04:39,  6.49s/rank]

Error :0.2502142611425768
Error :0.697327580995821
Error :0.5188712000786921
Error :0.42413176018010906
Error :0.37875865145222665
Error :0.3351908144400888
Error :0.30831643419711796
Error :0.29375902798248893
Error :0.2739390900602623
Error :0.26037232138111155


Ranks Progress:  67%|██████▋   | 87/129 [09:17<04:32,  6.48s/rank]

Error :0.24878638181510196
Error :0.6617124132922174
Error :0.5345621539793683
Error :0.4201889601663659
Error :0.37612499825693513
Error :0.3340011007701576
Error :0.3069278021953574
Error :0.28932471849560254
Error :0.2739046925417251
Error :0.25996371185511213


Ranks Progress:  68%|██████▊   | 88/129 [09:24<04:24,  6.44s/rank]

Error :0.25183078461837677
Error :0.6892444465399827
Error :0.524737912477715
Error :0.4367546994324722
Error :0.3870052178222941
Error :0.3418463080503317
Error :0.31061947321438965
Error :0.29160456844075
Error :0.2720067121781617
Error :0.2605978331385756


Ranks Progress:  69%|██████▉   | 89/129 [09:30<04:18,  6.46s/rank]

Error :0.24648459770495226
Error :0.6693358754700242
Error :0.5254995143258366
Error :0.4131783743518093
Error :0.3721834924163864
Error :0.3339056602841836
Error :0.3134210589231143
Error :0.28797908645129044
Error :0.2739495620300427
Error :0.25949811901601405


Ranks Progress:  70%|██████▉   | 90/129 [09:37<04:10,  6.43s/rank]

Error :0.2504269305143069
Error :0.715591292112727
Error :0.5744913869832874
Error :0.43677840769870757
Error :0.3849320560872199
Error :0.33841040412403633
Error :0.3112988736729393
Error :0.28618180888088185
Error :0.27078036608606965
Error :0.25799569388015714


Ranks Progress:  71%|███████   | 91/129 [09:43<04:04,  6.45s/rank]

Error :0.24727784697474928
Error :0.6789541297020616
Error :0.5236929133757928
Error :0.4377736051739384
Error :0.38076282339068435
Error :0.33228346030439104
Error :0.30719070956693606
Error :0.2892942250766434
Error :0.27048032409455697
Error :0.25518856479724356


Ranks Progress:  71%|███████▏  | 92/129 [09:50<03:58,  6.45s/rank]

Error :0.24930485886828152
Error :0.6799183233804532
Error :0.4989709942617707
Error :0.4252406349049481
Error :0.36794070647838856
Error :0.3444294348384908
Error :0.3114660495501014
Error :0.29396819880759983
Error :0.26876797293576143
Error :0.25704366623208297


Ranks Progress:  72%|███████▏  | 93/129 [09:56<03:51,  6.44s/rank]

Error :0.24728451557123618
Error :0.7107334939098774
Error :0.5138049244262655
Error :0.4446415591907252
Error :0.3633157827711844
Error :0.3300386539425469
Error :0.3211087274692473
Error :0.28782402905003557
Error :0.2766714273450586
Error :0.25636424495830273


Ranks Progress:  73%|███████▎  | 94/129 [10:02<03:45,  6.43s/rank]

Error :0.24890017810734186
Error :0.6478130937312264
Error :0.495376738283729
Error :0.438436876915951
Error :0.367996792875314
Error :0.33016335965224525
Error :0.3128368891964616
Error :0.28976577794076985
Error :0.2717766666662555
Error :0.26300352683401285


Ranks Progress:  74%|███████▎  | 95/129 [10:09<03:39,  6.44s/rank]

Error :0.24549795699757218
Error :0.688940796651326
Error :0.5345113826340743
Error :0.4299617778190946
Error :0.3784725508017522
Error :0.33613076825959876
Error :0.31890297659635714
Error :0.29051253453494114
Error :0.27243939201247513
Error :0.2592124031686443


Ranks Progress:  74%|███████▍  | 96/129 [10:15<03:33,  6.47s/rank]

Error :0.2440858798557549
Error :0.6636743477944993
Error :0.5082690496571385
Error :0.43811166728286755
Error :0.3658608034604123
Error :0.34598835424216967
Error :0.31085745674441545
Error :0.2900136512148444
Error :0.27026188820763236
Error :0.2575040972157784


Ranks Progress:  75%|███████▌  | 97/129 [10:22<03:25,  6.43s/rank]

Error :0.24483577407958393
Error :0.6876972489654797
Error :0.5333817290243674
Error :0.42040064770048763
Error :0.3640548070164097
Error :0.3373397846489133
Error :0.30933889152243177
Error :0.2874588257089159
Error :0.27205163024344037
Error :0.25761644942232814


Ranks Progress:  76%|███████▌  | 98/129 [10:28<03:19,  6.45s/rank]

Error :0.24535171010724882
Error :0.6692020786832722
Error :0.5520403488302321
Error :0.42602573401769017
Error :0.3689816151562068
Error :0.34803856379066067
Error :0.317629752559796
Error :0.29099118860045975
Error :0.27409534529829827
Error :0.25720434479468113


Ranks Progress:  77%|███████▋  | 99/129 [10:35<03:14,  6.47s/rank]

Error :0.25186977146429446
Error :0.6770975250169877
Error :0.5298795546423384
Error :0.4188591221343844
Error :0.37852415626524777
Error :0.338535184794233
Error :0.31362189411587965
Error :0.2908831457890664
Error :0.2707326813991847
Error :0.25789266459896093


Ranks Progress:  78%|███████▊  | 100/129 [10:42<03:10,  6.57s/rank]

Error :0.24365445941392225
Error :0.6790774204954995
Error :0.5164193674756826
Error :0.42154218776312613
Error :0.38971662806050944
Error :0.3356224818179713
Error :0.3060894070799164
Error :0.2890009700300753
Error :0.2712560397866797
Error :0.2568881614803895


Ranks Progress:  78%|███████▊  | 101/129 [10:48<03:02,  6.53s/rank]

Error :0.24790405992424952
Error :0.7159149709244162
Error :0.509482539378196
Error :0.4549373980613423
Error :0.36324372266851634
Error :0.3393192612336445
Error :0.3134912628258464
Error :0.29081064623042335
Error :0.27621909759969215
Error :0.2586560512465595


Ranks Progress:  79%|███████▉  | 102/129 [10:55<02:56,  6.54s/rank]

Error :0.24913584745380773
Error :0.6920090675152287
Error :0.5386958738987615
Error :0.42307954471075615
Error :0.37499786970302235
Error :0.34169318111528063
Error :0.31256884331607565
Error :0.28925079832556616
Error :0.27223189089572025
Error :0.25685692920855246


Ranks Progress:  80%|███████▉  | 103/129 [11:01<02:48,  6.50s/rank]

Error :0.2464611413818319
Error :0.6858435252539103
Error :0.5070962126962603
Error :0.42571098878740904
Error :0.37476696141724203
Error :0.34800582520055756
Error :0.3087337211377816
Error :0.29336283297433835
Error :0.27638589906312444
Error :0.26037116560691775


Ranks Progress:  81%|████████  | 104/129 [11:07<02:41,  6.47s/rank]

Error :0.24523793033031613
Error :0.6751864506759977
Error :0.5082328052446539
Error :0.4266187076750332
Error :0.3713362181085149
Error :0.33765600133616486
Error :0.31411076790996234
Error :0.2949233298828136
Error :0.2709150619170081
Error :0.2656597071086638


Ranks Progress:  81%|████████▏ | 105/129 [11:14<02:35,  6.48s/rank]

Error :0.24409333058632174
Error :0.7289930419245757
Error :0.5075704086648466
Error :0.4368788506650006
Error :0.37524846245391336
Error :0.34616230988210384
Error :0.31525145142374766
Error :0.29039169804700793
Error :0.27369039518072513
Error :0.25806495786374023


Ranks Progress:  82%|████████▏ | 106/129 [11:20<02:29,  6.49s/rank]

Error :0.24496431424801696
Error :0.7163175918033409
Error :0.5254198801510526
Error :0.43499157066647637
Error :0.3713705661839095
Error :0.34224661376394394
Error :0.31212488719062087
Error :0.2923255925117783
Error :0.27295260248772496
Error :0.2589715555638847


Ranks Progress:  83%|████████▎ | 107/129 [11:27<02:22,  6.46s/rank]

Error :0.24787033148316687
Error :0.6793225299218056
Error :0.5487346690126726
Error :0.43394502088360154
Error :0.38418654353101334
Error :0.3359655518161072
Error :0.306776489009406
Error :0.29089421382138
Error :0.2745851365613811
Error :0.25854097050219504


Ranks Progress:  84%|████████▎ | 108/129 [11:33<02:16,  6.48s/rank]

Error :0.24463686294494488
Error :0.7066596199443244
Error :0.5271427602621489
Error :0.42827933682930486
Error :0.38039796825847505
Error :0.34569802562195673
Error :0.30597245102737264
Error :0.290561324811781
Error :0.2741580436068244
Error :0.25718709427707437


Ranks Progress:  84%|████████▍ | 109/129 [11:40<02:09,  6.47s/rank]

Error :0.24324868234038008
Error :0.7088206345375125
Error :0.522808309410822
Error :0.4388260518543158
Error :0.3812461794183293
Error :0.34466498605507884
Error :0.31025841567339635
Error :0.29383052277024685
Error :0.27357819410216605
Error :0.25877595725863184


Ranks Progress:  85%|████████▌ | 110/129 [11:46<02:02,  6.47s/rank]

Error :0.2443760167137053
Error :0.6644894053615515
Error :0.5148829874005835
Error :0.4572988692573247
Error :0.38180687357189247
Error :0.35088797059268717
Error :0.3148552468740572
Error :0.2931205300584176
Error :0.2715479959809723
Error :0.25789390885061203


Ranks Progress:  86%|████████▌ | 111/129 [11:53<01:56,  6.48s/rank]

Error :0.24535707617386002
Error :0.6884611796800152
Error :0.5182860218034545
Error :0.4276927730379249
Error :0.376732022989988
Error :0.3391869117324508
Error :0.3154860660704159
Error :0.28667324081142775
Error :0.27183891519677716
Error :0.26083848416690303


Ranks Progress:  87%|████████▋ | 112/129 [11:59<01:50,  6.49s/rank]

Error :0.24436457317129362
Error :0.6938472981170464
Error :0.5393749811044836
Error :0.45452581511189816
Error :0.383041699982057
Error :0.33710934219022876
Error :0.3124065254572649
Error :0.29173135231439656
Error :0.2750389336423156
Error :0.2597273663995066


Ranks Progress:  88%|████████▊ | 113/129 [12:06<01:43,  6.44s/rank]

Error :0.2443196013552517
Error :0.6900354832676333
Error :0.523550533079746
Error :0.4366508470845527
Error :0.3803315679264499
Error :0.34137005788885344
Error :0.31369898228613896
Error :0.2869882211068215
Error :0.27447061686630414
Error :0.2578537742946847


Ranks Progress:  88%|████████▊ | 114/129 [12:12<01:36,  6.47s/rank]

Error :0.24465613000160666
Error :0.6781346222129915
Error :0.5141874390862264
Error :0.43566084320702536
Error :0.380108049197792
Error :0.336716954520445
Error :0.30166727753361017
Error :0.29499754887144625
Error :0.27691158895820717
Error :0.2587598331397778


Ranks Progress:  89%|████████▉ | 115/129 [12:18<01:29,  6.39s/rank]

Error :0.24735301719423022
Error :0.6992026145110829
Error :0.5461675746785563
Error :0.4281747052052626
Error :0.3760003576534086
Error :0.34118511088956915
Error :0.3104786668740404
Error :0.28975307173083764
Error :0.2736688394388145
Error :0.25751231469210206


Ranks Progress:  90%|████████▉ | 116/129 [12:24<01:19,  6.14s/rank]

Error :0.2461464658329126
Error :0.7004309117619721
Error :0.5109619301806163
Error :0.43269569169985356
Error :0.3674334431950341
Error :0.3328357258407279
Error :0.30908180933018436
Error :0.29037269563823614
Error :0.27225305642214764
Error :0.2580617198637349


Ranks Progress:  91%|█████████ | 117/129 [12:29<01:11,  5.96s/rank]

Error :0.24824247773202313
Error :0.6445165922434742
Error :0.5252468020575343
Error :0.4186351598973108
Error :0.3650524398863408
Error :0.34432165896212513
Error :0.31458061035493434
Error :0.2959920415999032
Error :0.2734255461118782
Error :0.2574972331403221


Ranks Progress:  91%|█████████▏| 118/129 [12:36<01:07,  6.15s/rank]

Error :0.24751960277328414
Error :0.7011921419921666
Error :0.5206337304462907
Error :0.4414295945390035
Error :0.3785948544114095
Error :0.33692719981769814
Error :0.3077553582685834
Error :0.2961474795390867
Error :0.272207351399497
Error :0.26141442065346376


Ranks Progress:  92%|█████████▏| 119/129 [12:42<01:02,  6.24s/rank]

Error :0.24592601023223118
Error :0.7227829817308387
Error :0.5106636067713438
Error :0.4343674395438792
Error :0.37773949603138496
Error :0.33670042808679923
Error :0.31325363820302016
Error :0.29120656715310983
Error :0.2706848573828984
Error :0.2606758826462499


Ranks Progress:  93%|█████████▎| 120/129 [12:49<00:56,  6.32s/rank]

Error :0.24374276810390058
Error :0.6918169103704523
Error :0.5420339362549302
Error :0.4218638531016979
Error :0.3755821041545987
Error :0.332655154000155
Error :0.30469532292461676
Error :0.2921800389768836
Error :0.27412889910605664
Error :0.2572488928665947


Ranks Progress:  94%|█████████▍| 121/129 [12:56<00:51,  6.43s/rank]

Error :0.2469167433245445
Error :0.6818917173821203
Error :0.5370728850423808
Error :0.4331236623930401
Error :0.36954340061648916
Error :0.34537959976121585
Error :0.3069133790074059
Error :0.2926134740424704
Error :0.2749651537275678
Error :0.2573166027243272


Ranks Progress:  95%|█████████▍| 122/129 [13:02<00:45,  6.48s/rank]

Error :0.2469720436281892
Error :0.7320692128692063
Error :0.51163720321665
Error :0.4300252843007415
Error :0.39155624939196687
Error :0.3394106562778416
Error :0.3126909761829726
Error :0.29387635862366684
Error :0.2717478177884715
Error :0.25691540403832375


Ranks Progress:  95%|█████████▌| 123/129 [13:09<00:38,  6.49s/rank]

Error :0.2450793903877514
Error :0.714915955897815
Error :0.5219453161280422
Error :0.412567391425746
Error :0.36900265319580117
Error :0.33940188241092206
Error :0.3127587241028728
Error :0.2894129854661072
Error :0.2721828772819495
Error :0.2614144287300146


Ranks Progress:  96%|█████████▌| 124/129 [13:15<00:32,  6.48s/rank]

Error :0.2440193603857177
Error :0.7230326636427572
Error :0.5355979671278797
Error :0.4365555061750562
Error :0.36686568588186247
Error :0.34139640523945464
Error :0.31648054154927413
Error :0.2894521425255434
Error :0.27293295843745163
Error :0.2610365299011319


Ranks Progress:  97%|█████████▋| 125/129 [13:22<00:25,  6.50s/rank]

Error :0.24816284440219638
Error :0.6905286745989575
Error :0.5610045161252568
Error :0.44544775723775104
Error :0.3710973459917542
Error :0.34446205671355046
Error :0.3127864150621519
Error :0.2903576175896909
Error :0.27060506003291485
Error :0.25920615648886086


Ranks Progress:  98%|█████████▊| 126/129 [13:28<00:19,  6.43s/rank]

Error :0.244590562535401
Error :0.6581331765978133
Error :0.5466098359431704
Error :0.43997040265084975
Error :0.36679972016797363
Error :0.3410131482658905
Error :0.3146607504032855
Error :0.28619371950858785
Error :0.2733786336148383
Error :0.257186972311124


Ranks Progress:  98%|█████████▊| 127/129 [13:35<00:12,  6.46s/rank]

Error :0.24614465139385686
Error :0.6747669085689657
Error :0.5161524245982636
Error :0.4261223851594924
Error :0.36931544771924096
Error :0.3418435049524618
Error :0.3148348841156274
Error :0.2895547173475489
Error :0.27824093308771125
Error :0.2581474026761341


Ranks Progress:  99%|█████████▉| 128/129 [13:40<00:06,  6.24s/rank]

Error :0.24619464044160919
Error :0.7122828580427869
Error :0.5630334868065253
Error :0.4459269651348106
Error :0.3901434591965976
Error :0.3416379342466799
Error :0.314695576613568
Error :0.2936365901467728
Error :0.271991786528246
Error :0.2570710718482284


Ranks Progress: 100%|██████████| 129/129 [13:46<00:00,  6.40s/rank]

Error :0.24450886564889032


Results successfully saved to Section_2_test_1_for_loadMatrixA_1.xlsx.


In [26]:
collect_low_rank_errors(A=loadMatrix_A_1, output_file='../Dataset/Section_2_test_2_for_loadMatrixA_1.csv')
collect_low_rank_errors(A=loadMatrix_A_2, output_file='../Dataset/Section_2_test_2_for_loadMatrixA_2.csv')
collect_low_rank_errors(A=loadMatrix_A_3, output_file='../Dataset/Section_2_test_2_for_loadMatrixA_3.csv')

Ranks Progress:   0%|          | 0/129 [00:00<?, ?rank/s]

Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0


Ranks Progress:   1%|          | 1/129 [00:05<12:32,  5.88s/rank]

Error :1.0
Error :0.9504192649843474
Error :0.9440374499488048
Error :0.9427072264467282
Error :0.9416234434056384
Error :0.9417250929357813
Error :0.941264925379735
Error :0.9408831422630048
Error :0.9410011178258328
Error :0.9407829339613573


Ranks Progress:   2%|▏         | 2/129 [00:12<13:20,  6.30s/rank]

Error :0.9404430762899549
Error :0.8996458234718834
Error :0.8903659479466018
Error :0.8854952424374849
Error :0.8861669258834713
Error :0.8839231034715307
Error :0.8826284870759408
Error :0.8825809002309085
Error :0.8823522617392937
Error :0.8815897773287893


Ranks Progress:   2%|▏         | 3/129 [00:18<13:11,  6.28s/rank]

Error :0.8811866430586165
Error :0.8571407402036122
Error :0.835126298936707
Error :0.8338795311234533
Error :0.8292294286491773
Error :0.8262452849241884
Error :0.8258307617824253
Error :0.8242956582920115
Error :0.8235431290420053
Error :0.8226435872590475


Ranks Progress:   3%|▎         | 4/129 [00:25<13:08,  6.31s/rank]

Error :0.8219882980158545
Error :0.8269909948336935
Error :0.7903121760220168
Error :0.7799846749183659
Error :0.77567938190587
Error :0.7695912691082795
Error :0.7675488405058397
Error :0.76753636178782
Error :0.7651191309125313
Error :0.7644625787167194


Ranks Progress:   4%|▍         | 5/129 [00:31<12:51,  6.23s/rank]

Error :0.7626606962291602
Error :0.7698997036077836
Error :0.7422831993003024
Error :0.7299187722505637
Error :0.7198294506429304
Error :0.7158901701145793
Error :0.7111948429291415
Error :0.708882229810097
Error :0.7071863278312847
Error :0.7054947976266175


Ranks Progress:   5%|▍         | 6/129 [00:37<12:54,  6.30s/rank]

Error :0.7049200140809346
Error :0.72056031432531
Error :0.6960854739925334
Error :0.6722913198795061
Error :0.6634610782057171
Error :0.6586529801266008
Error :0.6566944217236882
Error :0.6532070272276511
Error :0.6507086696702662
Error :0.6470215645902639


Ranks Progress:   5%|▌         | 7/129 [00:43<12:46,  6.28s/rank]

Error :0.646492353933788
Error :0.7339266098799114
Error :0.6516552538981928
Error :0.6331999298756774
Error :0.6137872308856299
Error :0.6052684208983341
Error :0.5995251909319242
Error :0.5954530463224411
Error :0.5948383816885884
Error :0.5921403614974438


Ranks Progress:   6%|▌         | 8/129 [00:49<12:26,  6.17s/rank]

Error :0.5879050000470749
Error :0.7170164727764958
Error :0.6398883556790165
Error :0.5835650702807937
Error :0.5653086244436593
Error :0.5526306072130727
Error :0.5403762336894083
Error :0.5396618529746459
Error :0.5359183783462749
Error :0.5336234307646927


Ranks Progress:   7%|▋         | 9/129 [00:55<12:09,  6.08s/rank]

Error :0.5313764606458526
Error :0.6932407057744983
Error :0.5908620567574945
Error :0.5527160661375712
Error :0.5118150515637225
Error :0.4974258414413697
Error :0.49398004738846735
Error :0.4868617406328081
Error :0.478512150233291
Error :0.4747433280511874


Ranks Progress:   8%|▊         | 10/129 [01:01<12:07,  6.11s/rank]

Error :0.4724757538969812
Error :0.6805744206435512
Error :0.5619239758634219
Error :0.4895563756932348
Error :0.47750797455243593
Error :0.45266827756646066
Error :0.44069413420242576
Error :0.4328105321923172
Error :0.42548175807960753
Error :0.4184656583922068


Ranks Progress:   9%|▊         | 11/129 [01:07<12:01,  6.12s/rank]

Error :0.4180457327370715
Error :0.704034303017373
Error :0.5549836533608774
Error :0.49262690993193275
Error :0.451761490555007
Error :0.43281765333924915
Error :0.4184427343551945
Error :0.3983639663453185
Error :0.3935554134579049
Error :0.39212037599571564


Ranks Progress:   9%|▉         | 12/129 [01:13<11:52,  6.09s/rank]

Error :0.3927574397479206
Error :0.7084071596529093
Error :0.5606865699055495
Error :0.4815126591248041
Error :0.4224284061640076
Error :0.4105749339354365
Error :0.40256282842398416
Error :0.3858680537978529
Error :0.3807845901724704
Error :0.3735906826112373


Ranks Progress:  10%|█         | 13/129 [01:19<11:38,  6.03s/rank]

Error :0.370396031687502
Error :0.6952852000554718
Error :0.5413057330023051
Error :0.45169070978922443
Error :0.42648760682668463
Error :0.40594305997441077
Error :0.38680817863071615
Error :0.3780456758074655
Error :0.3721070443603877
Error :0.36636200040865113


Ranks Progress:  11%|█         | 14/129 [01:25<11:30,  6.00s/rank]

Error :0.35946915832367504
Error :0.7133291344058675
Error :0.5432725303818023
Error :0.45891794746096565
Error :0.40927203039899146
Error :0.3971349651381749
Error :0.37452112439235535
Error :0.3642014983982898
Error :0.3621638123466518
Error :0.35059071473052034


Ranks Progress:  12%|█▏        | 15/129 [01:31<11:19,  5.96s/rank]

Error :0.35070917870710183
Error :0.6861826436089721
Error :0.5372907948199723
Error :0.44667009032680577
Error :0.4129127317188754
Error :0.3842613685815176
Error :0.3716357439285727
Error :0.3593109066795644
Error :0.3485888293444432
Error :0.34452594382463225


Ranks Progress:  12%|█▏        | 16/129 [01:37<11:11,  5.94s/rank]

Error :0.3375186241880647
Error :0.7013653115505992
Error :0.5270916398473083
Error :0.4490168119389387
Error :0.416220688865915
Error :0.3862745867346047
Error :0.3627924308557056
Error :0.35498025292157537
Error :0.3404136701721559
Error :0.337547762425835


Ranks Progress:  13%|█▎        | 17/129 [01:43<11:05,  5.94s/rank]

Error :0.3319988172406903
Error :0.6887188961598087
Error :0.5263585128688224
Error :0.44668256931920186
Error :0.4014361656009798
Error :0.3823297065452337
Error :0.3582529775544271
Error :0.348592634582386
Error :0.33908274411362066
Error :0.33370945258639084


Ranks Progress:  14%|█▍        | 18/129 [01:49<11:01,  5.96s/rank]

Error :0.3266195395652839
Error :0.6949395857680241
Error :0.5394426245467057
Error :0.45999622217336805
Error :0.3972799548660423
Error :0.3790435322241762
Error :0.3578778408840899
Error :0.34163563179137624
Error :0.33652823360499234
Error :0.3253303028782694


Ranks Progress:  15%|█▍        | 19/129 [01:55<10:52,  5.93s/rank]

Error :0.319846961345879
Error :0.6720797286318495
Error :0.5122715458859833
Error :0.437637048778547
Error :0.39922270535635224
Error :0.3706589393050752
Error :0.3479920150481724
Error :0.33816961679452623
Error :0.3303116047575145
Error :0.3282113579000119


Ranks Progress:  16%|█▌        | 20/129 [02:01<10:51,  5.98s/rank]

Error :0.31614584580838645
Error :0.7005066191975378
Error :0.5329405084244243
Error :0.4333808906963328
Error :0.3999463927745765
Error :0.37086937823173627
Error :0.3553576089604053
Error :0.33252263441540486
Error :0.3303265902650537
Error :0.31909923260995765


Ranks Progress:  16%|█▋        | 21/129 [02:07<10:55,  6.07s/rank]

Error :0.3112310881042759
Error :0.7156713811504789
Error :0.5844218521440794
Error :0.432006663370444
Error :0.4002121935347668
Error :0.3609427837539762
Error :0.35084796197287693
Error :0.33672736584053886
Error :0.32144472067380314
Error :0.31402826484147484


Ranks Progress:  17%|█▋        | 22/129 [02:14<11:12,  6.28s/rank]

Error :0.30851375825007493
Error :0.7050169593892409
Error :0.5097386530675209
Error :0.4397951647520483
Error :0.3882923805113767
Error :0.3671381319643114
Error :0.3491487560390616
Error :0.3329707873005373
Error :0.3195826098343636
Error :0.3152899523315569


Ranks Progress:  18%|█▊        | 23/129 [02:21<11:31,  6.52s/rank]

Error :0.308001054532112
Error :0.7045711873695417
Error :0.5434284035731156
Error :0.44703656930073454
Error :0.3879365460925232
Error :0.3633358100538251
Error :0.3392588435310698
Error :0.3249384733662754
Error :0.3182339699955421
Error :0.3085893051763206


Ranks Progress:  19%|█▊        | 24/129 [02:28<11:42,  6.69s/rank]

Error :0.30095515015528207
Error :0.7022131066403641
Error :0.5129008666098327
Error :0.42175745602212583
Error :0.3905094995306442
Error :0.3650264896883841
Error :0.3353863781951234
Error :0.3272658867714051
Error :0.32297818208837736
Error :0.30545761111521386


Ranks Progress:  19%|█▉        | 25/129 [02:35<11:27,  6.61s/rank]

Error :0.30072347453622716
Error :0.7111476347397567
Error :0.5070658879446244
Error :0.4394300074611128
Error :0.3845160578689296
Error :0.3520696908032302
Error :0.33689302793738635
Error :0.3234088764325403
Error :0.31356288860119663
Error :0.3070099611895875


Ranks Progress:  20%|██        | 26/129 [02:41<11:12,  6.53s/rank]

Error :0.29607154338146746
Error :0.68900851864503
Error :0.5218567887086735
Error :0.4236680215255165
Error :0.3893583750450124
Error :0.35196824946109756
Error :0.33780287570941264
Error :0.3196887112784679
Error :0.3082868671861708
Error :0.2999257921960667


Ranks Progress:  21%|██        | 27/129 [02:47<10:54,  6.42s/rank]

Error :0.29527992323687685
Error :0.6939979917083272
Error :0.5104240892219538
Error :0.4289534369871344
Error :0.38553003140509556
Error :0.3621609226792967
Error :0.3293795068651794
Error :0.3205099506938752
Error :0.3059638708754362
Error :0.3029687062745333


Ranks Progress:  22%|██▏       | 28/129 [02:53<10:36,  6.30s/rank]

Error :0.29229523380067657
Error :0.7078768539031883
Error :0.5271175777484424
Error :0.45020712379072236
Error :0.3900537746508349
Error :0.3568633156750434
Error :0.3304071572478405
Error :0.3193093697940044
Error :0.3095971197561083
Error :0.29604607474937744


Ranks Progress:  22%|██▏       | 29/129 [02:59<10:29,  6.29s/rank]

Error :0.2926477943137274
Error :0.6727826002333188
Error :0.5356690460752487
Error :0.4236057034752058
Error :0.39302386895117536
Error :0.3640086084648102
Error :0.32627614749568024
Error :0.3156271860067854
Error :0.30431328553537973
Error :0.2945869891526402


Ranks Progress:  23%|██▎       | 30/129 [03:05<10:13,  6.20s/rank]

Error :0.2888743522399164
Error :0.6820278360896216
Error :0.5173052266076292
Error :0.42666302560857566
Error :0.38865238761798704
Error :0.3448760110844924
Error :0.33413404122849927
Error :0.31447878266159146
Error :0.30562402551069584
Error :0.29475882596395486


Ranks Progress:  24%|██▍       | 31/129 [03:11<09:56,  6.09s/rank]

Error :0.28493526663276136
Error :0.6807623411263414
Error :0.5322005696461737
Error :0.4511879598590489
Error :0.3945057437254037
Error :0.3571593158864302
Error :0.33263051168936053
Error :0.3153247134810936
Error :0.3016538409868562
Error :0.2916339464607654


Ranks Progress:  25%|██▍       | 32/129 [03:17<09:49,  6.07s/rank]

Error :0.28197697154494533
Error :0.6802274235491267
Error :0.5110212654253671
Error :0.42795910127997694
Error :0.38050989034283306
Error :0.3432527901064037
Error :0.32823760745708963
Error :0.31248514358797363
Error :0.2999691641945336
Error :0.29076089425717616


Ranks Progress:  26%|██▌       | 33/129 [03:23<09:41,  6.05s/rank]

Error :0.2841521164785686
Error :0.6836442740640384
Error :0.5094390850424458
Error :0.413944459995094
Error :0.3769657554270748
Error :0.3461642607525706
Error :0.32702932844195143
Error :0.30801114252710726
Error :0.2995537117891263
Error :0.29172985586772643


Ranks Progress:  26%|██▋       | 34/129 [03:30<09:40,  6.11s/rank]

Error :0.2836614584508517
Error :0.6926067082753278
Error :0.49027984484881065
Error :0.430866404438219
Error :0.36810184751955966
Error :0.34027405499394975
Error :0.3258378981344603
Error :0.3102156861562054
Error :0.2964610327848228
Error :0.2902923215884106


Ranks Progress:  27%|██▋       | 35/129 [03:36<09:33,  6.11s/rank]

Error :0.28357204460471963
Error :0.6953106476883631
Error :0.4809874381128052
Error :0.4422409190092147
Error :0.3763415738451567
Error :0.3438198621587779
Error :0.3192563088321358
Error :0.3094712613749196
Error :0.29956861807268415
Error :0.2901731601770791


Ranks Progress:  28%|██▊       | 36/129 [03:42<09:22,  6.05s/rank]

Error :0.27795834196831654
Error :0.6864635576450708
Error :0.5288446085464746
Error :0.4272794738625881
Error :0.3824631468730256
Error :0.337365356344294
Error :0.3184116726868206
Error :0.3068522811899179
Error :0.2937835030701741
Error :0.2864826004856482


Ranks Progress:  29%|██▊       | 37/129 [03:48<09:22,  6.12s/rank]

Error :0.2803199097915447
Error :0.7079481216223368
Error :0.507909345913561
Error :0.4384438547545912
Error :0.36803539328496226
Error :0.34338439853479213
Error :0.3211514170503247
Error :0.30637878146263076
Error :0.29494012432226496
Error :0.28605637214902013


Ranks Progress:  29%|██▉       | 38/129 [03:54<09:10,  6.05s/rank]

Error :0.2760346047559293
Error :0.7058839495745286
Error :0.5242866680476311
Error :0.43200839964193427
Error :0.38401587967862916
Error :0.3538669099987543
Error :0.3220414174135757
Error :0.308286803210048
Error :0.2906570949342849
Error :0.28072940685621844


Ranks Progress:  30%|███       | 39/129 [04:01<09:26,  6.29s/rank]

Error :0.2784492045542763
Error :0.6865575001767943
Error :0.5187784196483729
Error :0.42097098236573716
Error :0.3690648948506802
Error :0.3398053379265096
Error :0.3186177177603237
Error :0.3097303201344212
Error :0.29192693227158817
Error :0.2814757453695055


Ranks Progress:  31%|███       | 40/129 [04:07<09:32,  6.44s/rank]

Error :0.27280819303989207
Error :0.7129984416851772
Error :0.5196784480737915
Error :0.418815674624928
Error :0.3725255064670516
Error :0.33993356998975893
Error :0.3196469813630732
Error :0.30154143542131273
Error :0.29450278128069335
Error :0.27986543570836475


Ranks Progress:  32%|███▏      | 41/129 [04:14<09:28,  6.46s/rank]

Error :0.27232844129442624
Error :0.6815964388888063
Error :0.5537754991263962
Error :0.4349399487489614
Error :0.3784942698550389
Error :0.34652003511985247
Error :0.3200403126074481
Error :0.3026422192339347
Error :0.28964972459831756
Error :0.2812588634714633


Ranks Progress:  33%|███▎      | 42/129 [04:20<09:07,  6.29s/rank]

Error :0.2742035524559316
Error :0.6619348133900608
Error :0.5145684711100693
Error :0.4337643592191773
Error :0.3778030007386153
Error :0.3508312902709251
Error :0.31727961720544795
Error :0.30310030761880863
Error :0.2905503875033541
Error :0.2783795585382874


Ranks Progress:  33%|███▎      | 43/129 [04:25<08:39,  6.04s/rank]

Error :0.2744926819355676
Error :0.682860496728109
Error :0.5257984016759931
Error :0.437230450067721
Error :0.37638282374298954
Error :0.34243438272306076
Error :0.3180606877029229
Error :0.2950176024468966
Error :0.28882791924835005
Error :0.2795160185043129


Ranks Progress:  34%|███▍      | 44/129 [04:31<08:31,  6.01s/rank]

Error :0.2707191188421694
Error :0.6800659668667294
Error :0.5208477961022471
Error :0.423278472500089
Error :0.36151526938588696
Error :0.3446593972779385
Error :0.3148776953045769
Error :0.30389300161758126
Error :0.294552894285886
Error :0.28026543187710745


Ranks Progress:  35%|███▍      | 45/129 [04:37<08:21,  5.97s/rank]

Error :0.2708912268615179
Error :0.7032465167213202
Error :0.5234254929694698
Error :0.4271738757880984
Error :0.3742249765282496
Error :0.34753380577011656
Error :0.32417528158690645
Error :0.29415340840438936
Error :0.29177352088222064
Error :0.28005006089015105


Ranks Progress:  36%|███▌      | 46/129 [04:43<08:16,  5.98s/rank]

Error :0.26876941961153833
Error :0.6707545579368602
Error :0.533828911791419
Error :0.4376936638301573
Error :0.371244029935967
Error :0.3455650348485977
Error :0.3160314825490038
Error :0.30711046078062504
Error :0.2849627529390198
Error :0.28011816534831147


Ranks Progress:  36%|███▋      | 47/129 [04:49<08:14,  6.02s/rank]

Error :0.2681525255729001
Error :0.6827470415686434
Error :0.5264299466661687
Error :0.43588829641685084
Error :0.37627809331601114
Error :0.3412424199183134
Error :0.3153088218861115
Error :0.29992499602902006
Error :0.29053186859849256
Error :0.2769273824963341


Ranks Progress:  37%|███▋      | 48/129 [04:55<08:10,  6.05s/rank]

Error :0.26630200420183453
Error :0.694333915996213
Error :0.5143155916286318
Error :0.4550013097352007
Error :0.3680190349093566
Error :0.3480060023461377
Error :0.31915578613985945
Error :0.2961983738616841
Error :0.2850059973804076
Error :0.27905331522606464


Ranks Progress:  38%|███▊      | 49/129 [05:02<08:22,  6.28s/rank]

Error :0.2672848155062539
Error :0.709287091944243
Error :0.5328328325198016
Error :0.44780421644207974
Error :0.37174048381191493
Error :0.34380626358222477
Error :0.3101181032199451
Error :0.2991383067221653
Error :0.2852497014404279
Error :0.2754734757768615


Ranks Progress:  39%|███▉      | 50/129 [05:08<08:18,  6.31s/rank]

Error :0.2667289509481712
Error :0.7001392215386647
Error :0.5142244617794683
Error :0.44535097042119537
Error :0.3763315474789348
Error :0.34372106474466985
Error :0.31536745861305454
Error :0.2981699059992848
Error :0.28711184445302473
Error :0.2729254386374392


Ranks Progress:  40%|███▉      | 51/129 [05:15<08:19,  6.41s/rank]

Error :0.2668943180447655
Error :0.7117994367863495
Error :0.5506386651528903
Error :0.4367024636443561
Error :0.3753034956766139
Error :0.3446634735739977
Error :0.3089258135390219
Error :0.29357158652295473
Error :0.2808323655578269
Error :0.2792086342418267


Ranks Progress:  40%|████      | 52/129 [05:22<08:13,  6.41s/rank]

Error :0.26282450780834554
Error :0.7205599012973453
Error :0.5462065546565058
Error :0.43017026994646307
Error :0.3692892726265569
Error :0.342728655288558
Error :0.3153648819169235
Error :0.29136390825897235
Error :0.28327291218490197
Error :0.27219010156672485


Ranks Progress:  41%|████      | 53/129 [05:29<08:41,  6.86s/rank]

Error :0.2643491429306637
Error :0.6960141565868059
Error :0.5148197883400737
Error :0.44371996654207363
Error :0.38232163841935934
Error :0.3388658170217494
Error :0.31761452154300285
Error :0.29473550706096185
Error :0.2839382382380209
Error :0.273370784874691


Ranks Progress:  42%|████▏     | 54/129 [05:36<08:27,  6.76s/rank]

Error :0.2649362676826377
Error :0.6800603447768371
Error :0.5265492792919559
Error :0.42988152130854784
Error :0.3694387734833102
Error :0.33948925035524014
Error :0.31207374613988265
Error :0.29433067734709284
Error :0.2810544601350612
Error :0.2693485732491734


Ranks Progress:  43%|████▎     | 55/129 [05:43<08:19,  6.75s/rank]

Error :0.2623833954183208
Error :0.6682654271644772
Error :0.517058056998936
Error :0.42341420305493177
Error :0.37120857033641397
Error :0.33655936874387576
Error :0.31950277152968665
Error :0.2952045736160326
Error :0.2828954480537388
Error :0.2693115090707215


Ranks Progress:  43%|████▎     | 56/129 [05:49<08:00,  6.58s/rank]

Error :0.26424957493537593
Error :0.6885223151470722
Error :0.525436779228791
Error :0.4288677542040121
Error :0.35981927170739003
Error :0.33434896261316815
Error :0.30570017188487364
Error :0.2960300949277082
Error :0.28127155947329713
Error :0.27048626736909875


Ranks Progress:  44%|████▍     | 57/129 [05:55<07:48,  6.51s/rank]

Error :0.2631263856295663
Error :0.6793277387009333
Error :0.548422207449913
Error :0.41941206759880306
Error :0.38294103547299185
Error :0.3408249804087908
Error :0.30978618555918414
Error :0.29545952616993126
Error :0.2841777250489493
Error :0.27389118661465706


Ranks Progress:  45%|████▍     | 58/129 [06:02<07:48,  6.60s/rank]

Error :0.26190429848355995
Error :0.7102865750000408
Error :0.49749857415134674
Error :0.4270412319781057
Error :0.3781349583120865
Error :0.34641236338323544
Error :0.3172395990609878
Error :0.2941133487953206
Error :0.2810725137165099
Error :0.2687592434265379


Ranks Progress:  46%|████▌     | 59/129 [06:08<07:34,  6.49s/rank]

Error :0.26076119808908615
Error :0.6909780129409651
Error :0.5191803514738476
Error :0.42116974914708044
Error :0.3918555053534981
Error :0.33655420805442093
Error :0.3143699125893433
Error :0.29136863282554487
Error :0.2795928721949214
Error :0.27078220369569495


Ranks Progress:  47%|████▋     | 60/129 [06:15<07:28,  6.51s/rank]

Error :0.26364661644854975
Error :0.6927796984103588
Error :0.5110663366165502
Error :0.41976660122095916
Error :0.3821107617741177
Error :0.34859547964792653
Error :0.3195876827322286
Error :0.2915953782902506
Error :0.2786440027377183
Error :0.266138240181257


Ranks Progress:  47%|████▋     | 61/129 [06:21<07:23,  6.52s/rank]

Error :0.2596853940946258
Error :0.7335135322473709
Error :0.5163328779583238
Error :0.421639526829901
Error :0.38497006549904433
Error :0.35274037622418614
Error :0.3098320229441381
Error :0.2972387286789015
Error :0.27954794177707937
Error :0.27322380175360705


Ranks Progress:  48%|████▊     | 62/129 [06:27<07:08,  6.40s/rank]

Error :0.2559162708821915
Error :0.6750593211648701
Error :0.5243184873527017
Error :0.4302544730913311
Error :0.37917435050394865
Error :0.33184765107261754
Error :0.31140898137902984
Error :0.2947923438722099
Error :0.27633249089074774
Error :0.2685153788522817


Ranks Progress:  49%|████▉     | 63/129 [06:34<07:01,  6.39s/rank]

Error :0.2588945228787132
Error :0.6821986445238788
Error :0.5164768049749943
Error :0.43148238960277574
Error :0.3743925589986839
Error :0.3417897499030043
Error :0.3086837265569991
Error :0.2872349308896392
Error :0.27927139830267855
Error :0.2649049410744926


Ranks Progress:  50%|████▉     | 64/129 [06:40<06:51,  6.33s/rank]

Error :0.25768992588380885
Error :0.6835025741337202
Error :0.518353560173059
Error :0.4300114764150111
Error :0.3735287531910921
Error :0.33434242849203416
Error :0.30634668943566484
Error :0.2935916657554362
Error :0.2765806805157719
Error :0.2643583456733372


Ranks Progress:  50%|█████     | 65/129 [06:46<06:44,  6.31s/rank]

Error :0.2597567549882219
Error :0.7266007983454451
Error :0.5066103719004907
Error :0.4301736034373481
Error :0.3874161472262373
Error :0.33630845809985
Error :0.3069920106032168
Error :0.29064070717861323
Error :0.2769000501401954
Error :0.2659880686164577


Ranks Progress:  51%|█████     | 66/129 [06:53<06:37,  6.31s/rank]

Error :0.2575271778997096
Error :0.7143518845422486
Error :0.5464220258754334
Error :0.4302521258872876
Error :0.3768968875927895
Error :0.3364062014276159
Error :0.3227988936445543
Error :0.29208701066658305
Error :0.2794786512924228
Error :0.2655187035404218


Ranks Progress:  52%|█████▏    | 67/129 [06:59<06:31,  6.32s/rank]

Error :0.25594149277695055
Error :0.7153236672351505
Error :0.5295358484425201
Error :0.4428207954432162
Error :0.3715017425885828
Error :0.33229420291130685
Error :0.313390195270281
Error :0.2930964574417451
Error :0.2783895374132792
Error :0.2643706952019423


Ranks Progress:  53%|█████▎    | 68/129 [07:05<06:28,  6.37s/rank]

Error :0.2572693256865573
Error :0.7006128498970222
Error :0.5381289212303361
Error :0.4430710024754991
Error :0.3712719241436871
Error :0.34583306136890346
Error :0.31627486803730753
Error :0.2917669109836911
Error :0.2748203599470201
Error :0.2631578129573107


Ranks Progress:  53%|█████▎    | 69/129 [07:13<06:36,  6.61s/rank]

Error :0.25193236782851175
Error :0.6629293935510248
Error :0.5130239327713663
Error :0.41678424800767805
Error :0.3753206509610473
Error :0.3409691346939248
Error :0.3085800245027138
Error :0.28847334105572925
Error :0.27652722597166934
Error :0.26093892953250925


Ranks Progress:  54%|█████▍    | 70/129 [07:19<06:28,  6.58s/rank]

Error :0.2554482834152511
Error :0.6968595441860993
Error :0.512739229167607
Error :0.4534028311210765
Error :0.3858852568331095
Error :0.3399640051063548
Error :0.3146517642355063
Error :0.2909427154298394
Error :0.2781993160397996
Error :0.266415769108343


Ranks Progress:  55%|█████▌    | 71/129 [07:25<06:11,  6.41s/rank]

Error :0.25405075947408906
Error :0.6790712157686153
Error :0.51870868773373
Error :0.44298132011614977
Error :0.38383301370059314
Error :0.3384326519959981
Error :0.3133895810491136
Error :0.295121217342177
Error :0.27783332268076744
Error :0.2625210674977388


Ranks Progress:  56%|█████▌    | 72/129 [07:31<05:57,  6.27s/rank]

Error :0.2567620748021547
Error :0.6886357210904557
Error :0.5084489985261837
Error :0.4468447577027147
Error :0.3659046998502154
Error :0.33835057212798986
Error :0.3137950537587939
Error :0.2917102071975097
Error :0.2777623607611537
Error :0.2639784708200704


Ranks Progress:  57%|█████▋    | 73/129 [07:37<05:46,  6.18s/rank]

Error :0.25332957917581783
Error :0.6835716014204639
Error :0.5278767442651777
Error :0.4207704200164163
Error :0.37612525922620377
Error :0.3384703913694045
Error :0.32061851658825075
Error :0.29105011286638843
Error :0.2757704336259171
Error :0.26351596966057717


Ranks Progress:  57%|█████▋    | 74/129 [07:43<05:36,  6.11s/rank]

Error :0.2547867084170268
Error :0.6878633394327911
Error :0.5056021537303704
Error :0.44643439453080214
Error :0.38250939950544954
Error :0.3421263845462299
Error :0.30881616494751357
Error :0.28933106808615733
Error :0.27687039780585293
Error :0.26542123833148423


Ranks Progress:  58%|█████▊    | 75/129 [07:49<05:26,  6.05s/rank]

Error :0.25428651368368715
Error :0.6953457713706983
Error :0.5085693550920395
Error :0.4214890748941745
Error :0.38130586358587365
Error :0.3554108643616121
Error :0.30731886741854003
Error :0.29366521950218244
Error :0.27681257716850866
Error :0.26332489038190104


Ranks Progress:  59%|█████▉    | 76/129 [07:55<05:20,  6.05s/rank]

Error :0.25296581703450105
Error :0.6910500220633514
Error :0.5352829050452926
Error :0.4637677073254993
Error :0.38815204765452205
Error :0.33849377857359464
Error :0.3172628644193862
Error :0.2909538174123961
Error :0.27238087879880196
Error :0.26330382057973056


Ranks Progress:  60%|█████▉    | 77/129 [08:01<05:13,  6.03s/rank]

Error :0.25234012764504427
Error :0.6961528377309075
Error :0.5421208857115595
Error :0.436453630342017
Error :0.3743281464132809
Error :0.35024987959608417
Error :0.30988676118743097
Error :0.2894448750425942
Error :0.27369082480670565
Error :0.26127955841309786


Ranks Progress:  60%|██████    | 78/129 [08:07<05:06,  6.00s/rank]

Error :0.25366753549865556
Error :0.6425350928985823
Error :0.5207913728862326
Error :0.4393479046130715
Error :0.3716331387628997
Error :0.3457948573014754
Error :0.30823395863982955
Error :0.2906674346387508
Error :0.2756260756416009
Error :0.26243973500970774


Ranks Progress:  61%|██████    | 79/129 [08:13<05:01,  6.03s/rank]

Error :0.25289179199425543
Error :0.6781084356049157
Error :0.5284981567608266
Error :0.4218483226785874
Error :0.3704755771151021
Error :0.33408169330178317
Error :0.3142104255150874
Error :0.2898716520847278
Error :0.2728421120102897
Error :0.26114293299540436


Ranks Progress:  62%|██████▏   | 80/129 [08:19<04:53,  6.00s/rank]

Error :0.2507951788664393
Error :0.7077783783418745
Error :0.5341892219606554
Error :0.42773718329636945
Error :0.37492548122350006
Error :0.3472985898991454
Error :0.3113692649397449
Error :0.29252652124876993
Error :0.2753728069694812
Error :0.2613684056003152


Ranks Progress:  63%|██████▎   | 81/129 [08:25<04:47,  5.99s/rank]

Error :0.254024533935653
Error :0.7363262773536066
Error :0.5252241432695873
Error :0.4341862827786908
Error :0.389014602329767
Error :0.3461806842413515
Error :0.3167247826447669
Error :0.29067371504113393
Error :0.2712693885203074
Error :0.2648925552833885


Ranks Progress:  64%|██████▎   | 82/129 [08:31<04:40,  5.98s/rank]

Error :0.249684764097174
Error :0.714532996121208
Error :0.49447691032189434
Error :0.42179784041880714
Error :0.38086414293502396
Error :0.33607669191631295
Error :0.316867133785834
Error :0.29017359133185266
Error :0.2699859908384948
Error :0.2594467033243979


Ranks Progress:  64%|██████▍   | 83/129 [08:37<04:36,  6.02s/rank]

Error :0.251785800959384
Error :0.6604666673595297
Error :0.506141159858388
Error :0.4109522823297297
Error :0.37257316797648965
Error :0.32614411451062875
Error :0.3145471589059701
Error :0.28775817658639824
Error :0.2715374445281565
Error :0.25771440109732685


Ranks Progress:  65%|██████▌   | 84/129 [08:43<04:30,  6.02s/rank]

Error :0.24676241550204914
Error :0.6728466476736106
Error :0.5441303521901576
Error :0.436618299978866
Error :0.359005135784511
Error :0.33925806487655785
Error :0.306677491548564
Error :0.28861987044470455
Error :0.2739696152898465
Error :0.2632351871775548


Ranks Progress:  66%|██████▌   | 85/129 [08:49<04:22,  5.98s/rank]

Error :0.2493337967950802
Error :0.7203723895294095
Error :0.5262845133309257
Error :0.42761650438189097
Error :0.3811068836935191
Error :0.33812471026280555
Error :0.3062205293339444
Error :0.28589020044736263
Error :0.27117591876015246
Error :0.2581840229527626


Ranks Progress:  67%|██████▋   | 86/129 [08:55<04:22,  6.10s/rank]

Error :0.24807015499943147
Error :0.6828276646962953
Error :0.500117007424198
Error :0.4389329152834607
Error :0.3844870398360063
Error :0.34470220080138125
Error :0.30840630628241095
Error :0.2885755943875614
Error :0.27202720681275366
Error :0.2615390309735556


Ranks Progress:  67%|██████▋   | 87/129 [09:01<04:15,  6.08s/rank]

Error :0.24836707384163384
Error :0.702381369901298
Error :0.5429689758609922
Error :0.4264390026873356
Error :0.3846492573596403
Error :0.33617031211694925
Error :0.30512586438606726
Error :0.2884054721630562
Error :0.2736012158363763
Error :0.25778694976586225


Ranks Progress:  68%|██████▊   | 88/129 [09:07<04:04,  5.96s/rank]

Error :0.252962885982498
Error :0.7126148178280315
Error :0.5319128839863057
Error :0.4441094199676905
Error :0.3810401870342645
Error :0.33707903621409496
Error :0.3212928372071971
Error :0.28936247599409065
Error :0.273547242983241
Error :0.25987398568110476


Ranks Progress:  69%|██████▉   | 89/129 [09:13<04:02,  6.06s/rank]

Error :0.24768492608585863
Error :0.6513451619170757
Error :0.5135795630208537
Error :0.4403146670422178
Error :0.38120036178831723
Error :0.3368729702895813
Error :0.31451560642535636
Error :0.287811507861635
Error :0.2724866575652695
Error :0.25918446988242533


Ranks Progress:  70%|██████▉   | 90/129 [09:19<03:55,  6.03s/rank]

Error :0.25366790769926734
Error :0.6956399068696535
Error :0.5161829390243796
Error :0.4294347923167367
Error :0.3755319033839174
Error :0.345215363125461
Error :0.31752048671300764
Error :0.29202403613883504
Error :0.27021302256507707
Error :0.2609245438701243


Ranks Progress:  71%|███████   | 91/129 [09:25<03:47,  5.97s/rank]

Error :0.24757117971660716
Error :0.6674426111237399
Error :0.5139079853489882
Error :0.4531641801113444
Error :0.38513196655860676
Error :0.3392505796308111
Error :0.312091297004688
Error :0.28874136247530197
Error :0.2710897059928989
Error :0.25833932201966897


Ranks Progress:  71%|███████▏  | 92/129 [09:31<03:40,  5.96s/rank]

Error :0.24812247499879406
Error :0.695816371415335
Error :0.5243378813875662
Error :0.4399177642493812
Error :0.3770644006348296
Error :0.33555946214950205
Error :0.3081097497362581
Error :0.28716644105066536
Error :0.2726091351239182
Error :0.2589749336529782


Ranks Progress:  72%|███████▏  | 93/129 [09:37<03:33,  5.93s/rank]

Error :0.24903026997946126
Error :0.6781567424205647
Error :0.5282931021993154
Error :0.4427778128445914
Error :0.3794986318710757
Error :0.33837354276699877
Error :0.31167222211046924
Error :0.29059044265085077
Error :0.2726349046503081
Error :0.25698449824783187


Ranks Progress:  73%|███████▎  | 94/129 [09:43<03:27,  5.93s/rank]

Error :0.2450649168852196
Error :0.6495092250278766
Error :0.5435972279078085
Error :0.4242930344382815
Error :0.3703761001638251
Error :0.3417108019071376
Error :0.3152589627962721
Error :0.28749863039093787
Error :0.2708565111363956
Error :0.2609144256017557


Ranks Progress:  74%|███████▎  | 95/129 [09:49<03:21,  5.94s/rank]

Error :0.24795772580549708
Error :0.7057480482609805
Error :0.49467623054969917
Error :0.4210307372823555
Error :0.37742513308932907
Error :0.3353820709720382
Error :0.30776014508323596
Error :0.2855373609591267
Error :0.2747819073332369
Error :0.2580350725042208


Ranks Progress:  74%|███████▍  | 96/129 [09:55<03:17,  5.97s/rank]

Error :0.24749222688088213
Error :0.7284751168114779
Error :0.5602594406523185
Error :0.4311606740734516
Error :0.37527451468729023
Error :0.3361739659211232
Error :0.3080368282067437
Error :0.28859788836078487
Error :0.2701250605648095
Error :0.2590994892844027


Ranks Progress:  75%|███████▌  | 97/129 [10:01<03:10,  5.97s/rank]

Error :0.2459138582587612
Error :0.7014931473022534
Error :0.5209986042450279
Error :0.42401911923740276
Error :0.38680055098996685
Error :0.3394790017807166
Error :0.30598005732213324
Error :0.2894207013027932
Error :0.2736933425237302
Error :0.25528582170321723


Ranks Progress:  76%|███████▌  | 98/129 [10:07<03:04,  5.96s/rank]

Error :0.24709732497410167
Error :0.6913345707511679
Error :0.5278567622609281
Error :0.41622562586872514
Error :0.37546919134102713
Error :0.34395745752394014
Error :0.30896135525581775
Error :0.2874668284864306
Error :0.27239414061779005
Error :0.2583129223827854


Ranks Progress:  77%|███████▋  | 99/129 [10:13<02:57,  5.93s/rank]

Error :0.2458161893971017
Error :0.7098109623429896
Error :0.5200001908619003
Error :0.4208828462141536
Error :0.3741305538229418
Error :0.3419297342025629
Error :0.30580017905201856
Error :0.28938339468751995
Error :0.2749069771613193
Error :0.25892511235491117


Ranks Progress:  78%|███████▊  | 100/129 [10:18<02:52,  5.93s/rank]

Error :0.2485267572761608
Error :0.6973255671690197
Error :0.48667026035529376
Error :0.425676352048482
Error :0.3723904581009963
Error :0.34242266674498284
Error :0.31165370657999336
Error :0.29099109463021633
Error :0.27145072337584414
Error :0.25810834623305406


Ranks Progress:  78%|███████▊  | 101/129 [10:24<02:45,  5.90s/rank]

Error :0.24548026095263561
Error :0.6858736426566259
Error :0.5180700126870671
Error :0.43233979685141277
Error :0.3776870639071411
Error :0.3347141775421727
Error :0.31246689842678244
Error :0.28923822929134974
Error :0.27615741194486576
Error :0.25657028356969513


Ranks Progress:  79%|███████▉  | 102/129 [10:30<02:40,  5.96s/rank]

Error :0.24723787896174382
Error :0.6677436955099454
Error :0.5477909042154457
Error :0.42635928733936523
Error :0.37302312284955613
Error :0.3373820200551029
Error :0.30925718315549294
Error :0.2911556987641232
Error :0.27548815839388996
Error :0.2571166934518426


Ranks Progress:  80%|███████▉  | 103/129 [10:36<02:34,  5.95s/rank]

Error :0.2474733827269212
Error :0.6706040259611674
Error :0.5253047855095996
Error :0.42752839122566766
Error :0.3636251994827379
Error :0.34100116998946906
Error :0.30806829230680094
Error :0.29206701081594266
Error :0.270643956042101
Error :0.25682814432070494


Ranks Progress:  81%|████████  | 104/129 [10:42<02:28,  5.94s/rank]

Error :0.24370750878998826
Error :0.6917327845015875
Error :0.542276049564599
Error :0.44108695131174197
Error :0.3762726974707524
Error :0.3366771547904762
Error :0.31681017046981735
Error :0.29006715188856863
Error :0.2736009879483168
Error :0.2548096467330238


Ranks Progress:  81%|████████▏ | 105/129 [10:48<02:22,  5.94s/rank]

Error :0.24668914890437407
Error :0.6670405989795339
Error :0.5498782388106896
Error :0.4436920083067273
Error :0.37814320022178427
Error :0.33730322268955315
Error :0.3154522782504568
Error :0.291225759877538
Error :0.27132287038590885
Error :0.25889204292550166


Ranks Progress:  82%|████████▏ | 106/129 [10:54<02:15,  5.90s/rank]

Error :0.24731602622918858
Error :0.7007801832043113
Error :0.5554779712171725
Error :0.43698620431668556
Error :0.3794657179023453
Error :0.3383989466172802
Error :0.31064196209615763
Error :0.28924102726546896
Error :0.2730224114885863
Error :0.25973585864524934


Ranks Progress:  83%|████████▎ | 107/129 [11:00<02:10,  5.93s/rank]

Error :0.2465799152417742
Error :0.6867138101438567
Error :0.504575894491592
Error :0.435923632580029
Error :0.37373064948921153
Error :0.32311704503423944
Error :0.3149193131712388
Error :0.28912272930772687
Error :0.2764953639004809
Error :0.2577256676293858


Ranks Progress:  84%|████████▎ | 108/129 [11:06<02:04,  5.91s/rank]

Error :0.2441358810744397
Error :0.690148766124985
Error :0.5470636022572998
Error :0.438819389173224
Error :0.37793430058425376
Error :0.3322895067281954
Error :0.30684238817916126
Error :0.29373446202123216
Error :0.2751991334859375
Error :0.25659731107666295


Ranks Progress:  84%|████████▍ | 109/129 [11:12<01:58,  5.91s/rank]

Error :0.24558962304486498
Error :0.7270749785705555
Error :0.5152649317701186
Error :0.4338773594717375
Error :0.3734957064966272
Error :0.34290551671970826
Error :0.31238257070673997
Error :0.28952114943357593
Error :0.2713668283829101
Error :0.25413211684799747


Ranks Progress:  85%|████████▌ | 110/129 [11:18<01:52,  5.91s/rank]

Error :0.2472763067990013
Error :0.689593011518408
Error :0.5311968976036439
Error :0.42018922395550257
Error :0.3597241675092283
Error :0.33452279333216367
Error :0.3083544346929186
Error :0.2940533645761953
Error :0.27244878157073543
Error :0.2598111398780864


Ranks Progress:  86%|████████▌ | 111/129 [11:24<01:46,  5.90s/rank]

Error :0.24573758495007192
Error :0.7275612632394873
Error :0.5362913801788022
Error :0.44382781403464716
Error :0.3749982143553013
Error :0.3363318825787526
Error :0.3018170856012339
Error :0.2895575367797756
Error :0.27049282288423027
Error :0.2562467772752496


Ranks Progress:  87%|████████▋ | 112/129 [11:29<01:40,  5.90s/rank]

Error :0.24608454079207606
Error :0.719762009466486
Error :0.5361527708446432
Error :0.44224307409505603
Error :0.37480356945356086
Error :0.33420831538706586
Error :0.31031246496605647
Error :0.2883916097835064
Error :0.27375904824213676
Error :0.2552398412041378


Ranks Progress:  88%|████████▊ | 113/129 [11:36<01:38,  6.17s/rank]

Error :0.24715271973895178
Error :0.6961471867916909
Error :0.5262074932992983
Error :0.4278179998727531
Error :0.3654325000188633
Error :0.3402362548253645
Error :0.30760600661051174
Error :0.29355928144579496
Error :0.2711896888609655
Error :0.2558771647966669


Ranks Progress:  88%|████████▊ | 114/129 [11:43<01:35,  6.39s/rank]

Error :0.24522332692166812
Error :0.68467951387407
Error :0.5393276126113478
Error :0.43495090240645434
Error :0.37101197608687947
Error :0.3309926194727323
Error :0.30894794791714525
Error :0.28801517908902924
Error :0.2792401641119832
Error :0.25739676400955513


Ranks Progress:  89%|████████▉ | 115/129 [11:50<01:31,  6.54s/rank]

Error :0.2468060294893902
Error :0.7078229891475052
Error :0.5489879247287589
Error :0.4390684875511793
Error :0.37123766431729244
Error :0.3411614163612776
Error :0.30946791806678337
Error :0.2915117657476745
Error :0.27410672317538776
Error :0.2613630751776267


Ranks Progress:  90%|████████▉ | 116/129 [11:58<01:29,  6.87s/rank]

Error :0.2452361978956559
Error :0.7082064415240243
Error :0.5394444731468473
Error :0.4275192688016899
Error :0.37149779051674703
Error :0.33426616475914295
Error :0.3149691005294675
Error :0.29138734951256506
Error :0.2745161127099062
Error :0.2606256300388339


Ranks Progress:  91%|█████████ | 117/129 [12:04<01:22,  6.85s/rank]

Error :0.24535270972691406
Error :0.689231794867616
Error :0.5259373525397332
Error :0.4238627021186793
Error :0.3714415027444032
Error :0.3419558218117626
Error :0.31821187902577375
Error :0.2871882803210186
Error :0.2731973537355216
Error :0.25979020187743246


Ranks Progress:  91%|█████████▏| 118/129 [12:11<01:14,  6.75s/rank]

Error :0.245991118250089
Error :0.6954040141192787
Error :0.5321429386107462
Error :0.44537131223038234
Error :0.37303464216048854
Error :0.333635822209732
Error :0.3206128004511856
Error :0.29286998123207003
Error :0.2749567223215197
Error :0.25834804364056085


Ranks Progress:  92%|█████████▏| 119/129 [12:18<01:07,  6.73s/rank]

Error :0.24560322442824273
Error :0.6739016043412172
Error :0.5520310273204244
Error :0.43738906286364987
Error :0.36392056696080105
Error :0.3421921772232274
Error :0.3157350463320437
Error :0.29406677992449815
Error :0.2712357539386747
Error :0.2581340027771606


Ranks Progress:  93%|█████████▎| 120/129 [12:24<00:59,  6.59s/rank]

Error :0.2471180238404716
Error :0.6705284313816285
Error :0.526386966195506
Error :0.43296481721186464
Error :0.3824501044779367
Error :0.33796238509234877
Error :0.3146299764777272
Error :0.2933465319604575
Error :0.27210318686594487
Error :0.2614368509267204


Ranks Progress:  94%|█████████▍| 121/129 [12:30<00:52,  6.54s/rank]

Error :0.24646249157749203
Error :0.7091027339974263
Error :0.5343955404872898
Error :0.42523338442057373
Error :0.3868964705556973
Error :0.33452650341805024
Error :0.3144261124275281
Error :0.2931757315717639
Error :0.2763180964295272
Error :0.2567738471931004


Ranks Progress:  95%|█████████▍| 122/129 [12:37<00:45,  6.46s/rank]

Error :0.2466604838973013
Error :0.7075118961499802
Error :0.5099684881706414
Error :0.4480563357333689
Error :0.37565606075325536
Error :0.3425527384041991
Error :0.3103472337125173
Error :0.2902972749284403
Error :0.2726049044210281
Error :0.25524860148484774


Ranks Progress:  95%|█████████▌| 123/129 [12:43<00:38,  6.47s/rank]

Error :0.2467660924833714
Error :0.7033474335621257
Error :0.523878492079337
Error :0.42863837495975005
Error :0.38521923815136555
Error :0.33709249649701595
Error :0.3096369912078761
Error :0.28869328208170564
Error :0.2713456141490506
Error :0.2632555949134575


Ranks Progress:  96%|█████████▌| 124/129 [12:49<00:31,  6.33s/rank]

Error :0.2463032309560638
Error :0.6892881902827301
Error :0.5173237588125739
Error :0.4370906077153284
Error :0.38316951103122354
Error :0.3380644217642921
Error :0.31005696107888275
Error :0.2933441792572922
Error :0.274412525930213
Error :0.2575332555762954


Ranks Progress:  97%|█████████▋| 125/129 [12:55<00:24,  6.24s/rank]

Error :0.24435031284870187
Error :0.7024969548677555
Error :0.5440417318769941
Error :0.4383029034887464
Error :0.3746978326904736
Error :0.33778996273091844
Error :0.30490179832766134
Error :0.28633470276017264
Error :0.2727589459993869
Error :0.25935303328689946


Ranks Progress:  98%|█████████▊| 126/129 [13:01<00:18,  6.18s/rank]

Error :0.2447478319905823
Error :0.7022855596067085
Error :0.49955636997088243
Error :0.4419053990124531
Error :0.3695364660674213
Error :0.3376696828090444
Error :0.3063996573273942
Error :0.2838972621813134
Error :0.27067830283933353
Error :0.2577974688260093


Ranks Progress:  98%|█████████▊| 127/129 [13:07<00:12,  6.14s/rank]

Error :0.24523560556231397
Error :0.6949681394291805
Error :0.5336808399665901
Error :0.42268269737743286
Error :0.38556847414114076
Error :0.3465060986330717
Error :0.31437620740159394
Error :0.2941959533129191
Error :0.27413908493783146
Error :0.25842664014773703


Ranks Progress:  99%|█████████▉| 128/129 [13:14<00:06,  6.20s/rank]

Error :0.24519618898843304
Error :0.679740225683944
Error :0.5402310335010104
Error :0.432428785082457
Error :0.37505983817706245
Error :0.33562981244260154
Error :0.3142845436502837
Error :0.2890442601046364
Error :0.27132348900505027
Error :0.25759559982247837


Ranks Progress: 100%|██████████| 129/129 [13:20<00:00,  6.21s/rank]

Error :0.24606492294663487


Results successfully saved to ../Dataset/Section_2_test_2_for_loadMatrixA_1.csv.


Ranks Progress:   0%|          | 0/129 [00:00<?, ?rank/s]

Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0
Error :1.0


Ranks Progress:   0%|          | 0/129 [00:03<?, ?rank/s]

Error :1.0


LinAlgError: Matrix is not positive definite