In [8]:
from dataset1 import *
import numpy as np
from scipy.linalg import solve_triangular
from numpy.linalg import eigh
import torch
from hadamard_transform import hadamard_transform
import time
import pandas as pd
import seaborn as sns
#test

## Define functions

In [9]:

def getError(A,B):
    return np.linalg.norm(A-B,ord='nuc')/np.linalg.norm(A,ord='nuc')

def fjlt(A, D, indices, direction):
    """
    Applies the Fast Johnson-Lindenstrauss Transform (FJLT) to a square matrix.

    Parameters:
    - A: Input square matrix (NumPy array of size n x m).
    - D: Diagonal vector of +1 and -1 (NumPy array of size n).
    - indices: Indices of the selected rows or columns for subsampling (NumPy array of size l).
    - direction: 'left' to apply FJLT from the left (on rows) or 'right' for the transpose case (on columns).

    Returns:
    - A_proj: Transformed matrix after applying FJLT and subsampling.
    """
    n, m = A.shape
    l = indices.shape[0]  # Sketch size
    if direction == 'left':  # FJLT applied to the rows of A
        assert len(D) == n, "The length of D must match the number of rows in A."
        assert (n & (n - 1) == 0), "The number of rows in A must be a power of 2."
        # Multiply each row of A by the corresponding element in D
        OmegaA = A * D[:, np.newaxis]
        # Apply the Fast Hadamard Transform to the rows
        OmegaA = hadamard_transform(torch.tensor(OmegaA.T)).numpy().T
        # Subsample the rows and scale
        OmegaA = OmegaA[indices, :] * np.sqrt(n / l)
        return np.ascontiguousarray(OmegaA)
    elif direction == 'right':  # FJLT applied to the columns of A
        # Multiply each column of A by the corresponding element in D
        AOmega = A * D[np.newaxis, :]
        # Apply the Fast Hadamard Transform to the columns
        AOmega = hadamard_transform(torch.tensor(AOmega)).numpy()
        # Subsample the columns and scale
        AOmega = AOmega[:, indices] * np.sqrt(n / l)
        return np.ascontiguousarray(AOmega)

def getLowRank(A, rank, sketch_dim, sketch_method='gaussian', good_conditionned=True, print_times=False):
    """
    Compute a low-rank approximation of the matrix A using sketching, 
    eigenvalue decomposition, and truncation. Optionally prints the time taken for each major operation.

    Parameters:
        A (numpy.ndarray): Original matrix (size m x n).
        rank (int): Desired rank for the approximation.
        sketch_dim (int): Dimension of the sketching subspace.
        sketch_method (str): Method used for sketching. Options are:
                             - 'gaussian': Uses a Gaussian random matrix for sketching.
                             - 'fjlt': Uses the Fast Johnson-Lindenstrauss Transform.
        good_conditionned (bool): If True, uses Cholesky decomposition for better conditioning. 
                                  Otherwise, uses eigenvalue decomposition.
        print_times (bool): If True, prints the time taken for each major operation.

    Returns:
        A_nyst_k (numpy.ndarray): Low-rank approximation of A (size m x m).
    """
    m = A.shape[0]
    B = None
    C = None

    start_time = time.time()

    # Apply sketching based on the selected method
    if sketch_method == 'fjlt':  # Use Fast Johnson-Lindenstrauss Transform for sketching
        D = np.random.choice([1, -1], size=m)
        indices = np.random.choice(m, size=sketch_dim, replace=False)
        sketch_start = time.time()
        C = fjlt(A, D, indices, direction='right')
        B = fjlt(C, D, indices, direction='left')
        if print_times:
            print(f"FJLT sketching completed in {time.time() - sketch_start:.6f} seconds.")

    elif sketch_method == 'gaussian':  # Use Gaussian random matrix for sketching
        Omega = np.random.normal(size=(m, sketch_dim))
        sketch_start = time.time()
        C = A @ Omega
        B = Omega.T @ C
        if print_times:
            print(f"Gaussian sketching completed in {time.time() - sketch_start:.6f} seconds.")
    else:
        raise ValueError("Méthode de sketching non reconnue. Choisissez 'gaussian' ou 'fjlt'.")

    if good_conditionned:
        # Use Cholesky decomposition
        cholesky_start = time.time()
        L = np.linalg.cholesky(B)
        if print_times:
            print(f"Cholesky decomposition completed in {time.time() - cholesky_start:.6f} seconds.")
        
        triangular_start = time.time()
        Z = solve_triangular(L, C.T, lower=True).T
        if print_times:
            print(f"Triangular solve completed in {time.time() - triangular_start:.6f} seconds.")
    else:
        # Use eigenvalue decomposition
        eigh_start = time.time()
        eig_v, V = eigh(B)
        if print_times:
            print(f"Eigenvalue decomposition completed in {time.time() - eigh_start:.6f} seconds.")
        
        truncate_start = time.time()
        truncate = eig_v > 0
        eig_v = eig_v[truncate]
        V = V[:, truncate]
        Z = C @ (V * (1 / np.sqrt(eig_v)))
        if print_times:
            print(f"Eigenvalue truncation and normalization completed in {time.time() - truncate_start:.6f} seconds.")

    qr_start = time.time()
    Q, R = np.linalg.qr(Z)
    if print_times:
        print(f"QR decomposition completed in {time.time() - qr_start:.6f} seconds.")

    svd_start = time.time()
    U, Sigma, _ = np.linalg.svd(R)
    if print_times:
        print(f"SVD completed in {time.time() - svd_start:.6f} seconds.")

    approx_start = time.time()
    U_hat = Q @ U[:, :rank]
    A_nyst_k = (U_hat * Sigma[:rank]**2) @ U_hat.T
    if print_times:
        print(f"Low-rank approximation construction completed in {time.time() - approx_start:.6f} seconds.")

    total_time = time.time() - start_time
    if print_times:
        print(f"Total computation time: {total_time:.6f} seconds.")
    error = getError(A,A_nyst_k)
    print(f"Error :{error}".format(error))

    return A_nyst_k, error 

## Tests

In [10]:
n = 2048
A = getExpMatrix(n,R=10)
print(A.shape)

(2048, 2048)


In [11]:
getLowRank(A,rank=128,sketch_dim=128,sketch_method='gaussian',good_conditionned=False,print_times=True)

Gaussian sketching completed in 0.016633 seconds.
Eigenvalue decomposition completed in 0.006657 seconds.
Eigenvalue truncation and normalization completed in 0.002259 seconds.
QR decomposition completed in 0.027455 seconds.
SVD completed in 0.004365 seconds.
Low-rank approximation construction completed in 0.013040 seconds.
Total computation time: 0.079953 seconds.
Error :1.2155091862342842e-14


(array([[ 1.00000000e+00,  1.34614542e-15, -1.00613962e-16, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.33920652e-15,  1.00000000e+00,  7.89299182e-16, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-7.28583860e-17,  7.19910243e-16,  1.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]),
 1.2155091862342842e-14)

In [ ]:
# getLowRank(A,rank=128,sketch_dim=128,sketch_method='fjlt',good_conditionned=False,print_times=True)

FJLT sketching completed in 0.144048 seconds.
Eigenvalue decomposition completed in 0.008370 seconds.
Eigenvalue truncation and normalization completed in 0.002851 seconds.
QR decomposition completed in 0.032139 seconds.
SVD completed in 0.006719 seconds.
Low-rank approximation construction completed in 0.010890 seconds.
Total computation time: 0.209292 seconds.
Error :3.924891156083275e-06


(array([[ 9.99998616e-01,  1.38412188e-06, -1.38412185e-06, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 1.38412188e-06,  9.99998616e-01,  1.38412190e-06, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [-1.38412185e-06,  1.38412190e-06,  9.99998616e-01, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        ...,
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]),
 3.924891156083275e-06)

## Section 2

We'll compute the error with respect to three matrices. 
1. polynomial decay (dimension 1024 * 1024) locates: 
2. exp decay locates:
3. ../Dataset/A_3_dataset_2_mnist.npy 
    denotes the matrix obtained from MNIST, with c=100
4. ../... mnist.npy with c = 10.

All four matrices are of dimension $1024 \times 1024$

In [13]:
# Loading matrices

loadMatrix_A_1 = np.load("../Dataset/A_1_polyDecayMatrix.npy")
print("matrix A_1")
print(loadMatrix_A_1.shape)
print(loadMatrix_A_1[:10,:5])

loadMatrix_A_2 = np.load("../Dataset/A_2_expDecayMatrix.npy")
print("matrix A_2")
print(loadMatrix_A_2.shape)
print(loadMatrix_A_2[:10,:5])

loadMatrix_A_3 = np.load("../Dataset/A_3_dataset_2_mnist.npy")
print("matrix A_3")
print(loadMatrix_A_3.shape)
print(loadMatrix_A_3[:10,:5])

loadMatrix_A_32 = np.load("../Dataset/A_3_dataset_2_mnist_C=10.npy")
print("matrix A_32")
print(loadMatrix_A_32.shape)
print(loadMatrix_A_32[:10,:5])



matrix A_1
(1024, 1024)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
matrix A_2
(1024, 1024)
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
matrix A_3
(1024, 1024)
[[1.         0.99127504 0.98824289 0.99001237 0.98907651]
 [0.99127504 1.         0.98715919 0.98829865 0.98930957]
 [0.98824289 0.98715919 1.         0.9898814  0.98994457]
 [0.99001237 0.98829865 0.9898814  1.         0.99126262]
 [0.98907651 0.98930957 0.98994457 0.99126262 1.        ]
 [0.98979753 0.98903161 0.98938555 0.99024257 0.99195122]
 [0.99100754 0.98756737 0.98972827 0.991512   0.9925866 ]
 [0.99278471 0.98967594 0.98934556 0.98962114 0.98935745]
 [0.99136177 0.98870132 0.99122707 0.99290202 0.9940263 ]
 [0.98989935 0.98824599 0.99277739 0.9911983

In [16]:
from tqdm import tqdm  # For progress tracking

def collect_low_rank_errors(
    A, 
    sketch_dims=[2, 4, 8, 16, 32, 64, 128], 
    is_good_conditionned=False, 
    sketch_method='gaussian', 
    output_file='Section_2_test_1_for_loadMatrixA_1.xlsx',
    matrix_name="MatrixA"
):
    """
    Computes errors for various ranks and sketch dimensions using the `getLowRank` function.

    Parameters:
    - A (np.ndarray): Input matrix.
    - sketch_dims (list of int): List of sketch dimensions to test.
    - is_good_conditionned (bool): Whether to use good-conditioned matrices in `getLowRank`.
    - sketch_method (str): Method for sketching ('gaussian' or other supported by `getLowRank`).
    - output_file (str): Path to the file where results are saved (.csv or .xlsx).
    - matrix_name (str): Name or identifier of the input matrix.

    Saves:
    - Results to a file with columns: "Sketch Dimension", "Approximation Rank", "Error Value",
      "Sketch Method", "Matrix Name".
    """
    print(A.shape)
    results = []
    
    # Iterate over each sketch_dim
    for sketch_dim in tqdm(sketch_dims, desc="Sketch Dimensions Progress", unit="dim"):
        ranks = list(range(0, sketch_dim + 1, 10))  # Generate ranks from 0 with step 5 up to sketch_dim
        for rank in ranks:
            # Compute the error for each rank
            _, error = getLowRank(
                A=A, 
                rank=rank, 
                sketch_dim=sketch_dim, 
                sketch_method=sketch_method, 
                good_conditionned=is_good_conditionned
            )
            # Append the result
            results.append({
                'Sketch Dimension': sketch_dim,
                'Approximation Rank': rank,
                'Error Value': error,
                'Sketch Method': sketch_method,
                'Matrix Name': matrix_name
            })
    
    # Convert results to a DataFrame for easier manipulation
    df = pd.DataFrame(results)

    # Save results to file
    if output_file.endswith('.csv'):
        df.to_csv(output_file, index=False)
    elif output_file.endswith('.xlsx'):
        df.to_excel(output_file, index=False, engine='openpyxl')
    else:
        raise ValueError("Output file must be either .csv or .xlsx.")
    
    print(f"Results saved to {output_file}.")



In [19]:
# collect_low_rank_errors(loadMatrix_A_1)
testList1 = [25, 50, 75, 100, 125, 150]
testList2 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
testList3 = [25, 50, 75, 100, 125, 150, 175, 200]

collect_low_rank_errors(A = loadMatrix_A_1, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=True, 
                        sketch_method='gaussian', 
                        output_file='../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_1.csv', matrix_name="loadMatrix_A_1")

collect_low_rank_errors(A = loadMatrix_A_2, 
                        sketch_dims = testList,  
                        is_good_conditionned=False, 
                        sketch_method='gaussian', 
                        output_file='../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_2.csv', matrix_name="loadMatrix_A_2")

collect_low_rank_errors(A = loadMatrix_A_3, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=False, 
                        sketch_method='gaussian', 
                        output_file='../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_3.csv', matrix_name="loadMatrix_A_3")

collect_low_rank_errors(A = loadMatrix_A_32, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=False, 
                        sketch_method='gaussian', 
                        output_file='../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_32.csv', matrix_name="loadMatrix_A_3")

collect_low_rank_errors(A = loadMatrix_A_1, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=True, 
                        sketch_method='fjlt', 
                        output_file='../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_1.csv', matrix_name="loadMatrix_A_1")

collect_low_rank_errors(A = loadMatrix_A_2, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=False, 
                        sketch_method='fjlt', 
                        output_file='../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_2.csv', matrix_name="loadMatrix_A_2")

collect_low_rank_errors(A = loadMatrix_A_3, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=False, 
                        sketch_method='fjlt', 
                        output_file='../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_3.csv', matrix_name="loadMatrix_A_3")

collect_low_rank_errors(A = loadMatrix_A_32, 
                        sketch_dims = [25, 50, 75, 100, 125, 150, 175, 200],  
                        is_good_conditionned=False, 
                        sketch_method='fjlt', 
                        output_file='../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_32.csv', matrix_name="loadMatrix_A_32")


(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.960772448919279


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:15,  2.17s/dim]

Error :0.9477751787564648
Error :1.0
Error :0.945709004216863
Error :0.9287808404175188
Error :0.9136843258015594
Error :0.9040175036572112


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:06<00:21,  3.53s/dim]

Error :0.8965860338365831
Error :1.0
Error :0.9362368596451409
Error :0.9139486715298505
Error :0.8999156883859274
Error :0.8870597008766996
Error :0.87684890641689
Error :0.8683415359785023


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:12<00:23,  4.65s/dim]

Error :0.8588695546283308
Error :1.0
Error :0.9263988807527623
Error :0.9027063327357425
Error :0.8869707476382939
Error :0.8729665841766335
Error :0.8603832379856753
Error :0.852686494433959
Error :0.8426122469894797
Error :0.8344647681203559
Error :0.8281872824882023


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:20<00:24,  6.06s/dim]

Error :0.819476253130446
Error :1.0
Error :0.9210289836418813
Error :0.8950474421243295
Error :0.8768268621995917
Error :0.8635269482349589
Error :0.8501360960299933
Error :0.839593788509231
Error :0.8291008520570403
Error :0.8207205868458931
Error :0.814199374351514
Error :0.801525371138179
Error :0.7950520077251098


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:30<00:22,  7.43s/dim]

Error :0.7874228621368832
Error :1.0
Error :0.9160083096572409
Error :0.8903366476576331
Error :0.8706819772986233
Error :0.8543377161852033
Error :0.8404789407430104
Error :0.8297297144544734
Error :0.8171433027391126
Error :0.8087007642282883
Error :0.7997359362168857
Error :0.7918180433650704
Error :0.7807252076950499
Error :0.7764761201212824
Error :0.7688931926932532
Error :0.7588854411766226


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:44<00:18,  9.46s/dim]

Error :0.752992214732647
Error :1.0
Error :0.9114094152069899
Error :0.8822131128220949
Error :0.862923677731566
Error :0.8484640783099506
Error :0.8321372931529533
Error :0.8210618984535589
Error :0.8110770661600077
Error :0.7989011434113596
Error :0.7894131087671289
Error :0.7812163895698666
Error :0.7710102636540012
Error :0.763661702565327
Error :0.7544072049223659
Error :0.7474352302502658
Error :0.7389558695038484
Error :0.7324841890924139


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [00:58<00:11, 11.09s/dim]

Error :0.7271171468615356
Error :1.0
Error :0.9081110286139747
Error :0.8785478687314806
Error :0.8587073095077944
Error :0.8398373371098852
Error :0.8264878264781346
Error :0.8129215961023923
Error :0.8020656425622205
Error :0.7898441641064657
Error :0.7807960969664004
Error :0.7700431312644284
Error :0.7605643762036564
Error :0.752134890578467
Error :0.744399202079449
Error :0.7363474630499834
Error :0.7300662455789968
Error :0.7215438097007516
Error :0.7150682473704252
Error :0.7072721327324273
Error :0.6994674577775648


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:15<00:00,  9.41s/dim]


Error :0.6931528773365375
Results saved to ../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_1.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/6 [00:00<?, ?dim/s]

Error :1.0
Error :0.1430313285307808


Sketch Dimensions Progress:  17%|█▋        | 1/6 [00:02<00:10,  2.10s/dim]

Error :0.03323931095877263
Error :1.0
Error :0.137845046488168
Error :0.013844700193580828
Error :0.0014494173521703846
Error :0.00028994942824950146


Sketch Dimensions Progress:  33%|███▎      | 2/6 [00:06<00:13,  3.40s/dim]

Error :0.0001589662005124218
Error :1.0
Error :0.1378123811166288
Error :0.013781493677472783
Error :0.0013783977162232536
Error :0.00013814394808061694
Error :1.4190437279719094e-05
Error :2.059550500383667e-06


Sketch Dimensions Progress:  50%|█████     | 3/6 [00:12<00:13,  4.49s/dim]

Error :7.069563964712664e-07
Error :1.0
Error :0.13781227122587192
Error :0.013781227576014438
Error :0.0013781241760949267
Error :0.00013781347054641182
Error :1.3783033754281556e-05
Error :1.3802572673997263e-06
Error :1.399388309335737e-07
Error :1.6011854294260266e-08
Error :4.080109885603103e-09


Sketch Dimensions Progress:  67%|██████▋   | 4/6 [00:20<00:11,  5.87s/dim]

Error :3.8667560007985204e-09
Error :1.0
Error :0.13781227096742182
Error :0.013781227098892682
Error :0.001378122713246463
Error :0.0001378122772166921
Error :1.3781234172314603e-05
Error :1.3781300427484854e-06
Error :1.3781974641472936e-07
Error :1.3790594218235174e-08
Error :1.3876379705682208e-09
Error :1.459208906102137e-10
Error :2.493850143598023e-11


Sketch Dimensions Progress:  83%|████████▎ | 5/6 [00:29<00:07,  7.21s/dim]

Error :1.7716361256636576e-11
Error :1.0
Error :0.1378122709660221
Error :0.013781227096620899
Error :0.001378122709684868
Error :0.00013781227100564725
Error :1.3781227138366452e-05
Error :1.3781227563707096e-06
Error :1.3781233478733278e-07
Error :1.3781327134280736e-08
Error :1.3781879084199967e-09
Error :1.3788217660825802e-10
Error :1.387935797193792e-11
Error :1.4752080520626106e-12
Error :2.631153882497779e-13
Error :2.0543911388747272e-13


Sketch Dimensions Progress: 100%|██████████| 6/6 [00:41<00:00,  6.98s/dim]


Error :1.038132336287948e-13
Results saved to ../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_2.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.00660085900472456


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:16,  2.40s/dim]

Error :0.005799255463323113
Error :1.0
Error :0.005902503512552623
Error :0.004631170768623631
Error :0.0040590971055518635
Error :0.003741501452876948


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:07<00:22,  3.80s/dim]

Error :0.0035646934387266486
Error :1.0
Error :0.005581692889955969
Error :0.004117223050088125
Error :0.003392889650963958
Error :0.0030174227237273372
Error :0.0027341718438037613
Error :0.0026023274928277653


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:13<00:24,  4.96s/dim]

Error :0.002486962837306091
Error :1.0
Error :0.005470007062414534
Error :0.0038784923653096383
Error :0.0030962052510724106
Error :0.0026512970705827965
Error :0.002386805427277888
Error :0.002166749748190517
Error :0.0020290746236958793
Error :0.0019309561929605756
Error :0.0018723326551822951


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:22<00:25,  6.47s/dim]

Error :0.0018649866486068285
Error :1.0
Error :0.005387693127433429
Error :0.00379911818032963
Error :0.002943277175144004
Error :0.0024388860291191293
Error :0.002143733831384961
Error :0.0019107566617899505
Error :0.0017845429397244904
Error :0.0016661233334907247
Error :0.0016220892077198324
Error :0.0015160984182137943
Error :0.001463245278509935


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:32<00:23,  7.98s/dim]

Error :0.0014354404354991004
Error :1.0
Error :0.00535240893939622
Error :0.0037316095431983876
Error :0.002859234435768883
Error :0.002333014852571266
Error :0.001975984305816792
Error :0.001765460773261135
Error :0.0015752088611653246
Error :0.001463656216420023
Error :0.0013773840701800035
Error :0.0013046937410004795
Error :0.0012378016827923799
Error :0.0011964840009976443
Error :0.0011754259196849377
Error :0.0011535398362270452


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:46<00:19,  9.81s/dim]

Error :0.001124115920790674
Error :1.0
Error :0.00532948588027263
Error :0.0036822390899420724
Error :0.002799294446046688
Error :0.002258456172988664
Error :0.0019124189514431315
Error :0.0016559889941023453
Error :0.0014747581695175047
Error :0.0013532154479453525
Error :0.0012574198957626117
Error :0.0011681586363892261
Error :0.001114696507433263
Error :0.0010567524788852936
Error :0.001017524897193063
Error :0.000975961248022939
Error :0.00095434994353319
Error :0.0009268754093701319


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [01:01<00:11, 11.57s/dim]

Error :0.000915093793601108
Error :1.0
Error :0.005316739390531614
Error :0.003653461309340208
Error :0.002760050077800091
Error :0.0022118460468733567
Error :0.0018318402604448742
Error :0.0015855408658469255
Error :0.0013901470994127948
Error :0.0012541351298637718
Error :0.0011521947332455208
Error :0.001062736919465617
Error :0.0010019859880708267
Error :0.0009339387157286007
Error :0.0008946020807986666
Error :0.0008631729815282873
Error :0.0008386181419303815
Error :0.0008062708526067803
Error :0.00078000218568895
Error :0.0007667041089896852
Error :0.0007474211148899807


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:19<00:00,  9.96s/dim]


Error :0.0007309239718451424
Results saved to ../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_3.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.5241095067241541


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:17,  2.46s/dim]

Error :0.499298503467032
Error :1.0
Error :0.48592868653843685
Error :0.44280903174760133
Error :0.4237994940965524
Error :0.413796268110491


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:07<00:23,  3.84s/dim]

Error :0.4038703150912103
Error :1.0
Error :0.4666475266285406
Error :0.4152589423276782
Error :0.3948358514370043
Error :0.37830847684435737
Error :0.3696966964851616
Error :0.36248598203313454


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:13<00:25,  5.06s/dim]

Error :0.36310804157797527
Error :1.0
Error :0.45589764694420504
Error :0.40159391659325727
Error :0.3718876663648201
Error :0.3576926379353234
Error :0.3450989662768925
Error :0.3365518851087366
Error :0.32991364425214437
Error :0.3277819703717474
Error :0.324675303658962


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:22<00:26,  6.62s/dim]

Error :0.31933342285998034
Error :1.0
Error :0.4500615621122009
Error :0.39153778229846947
Error :0.36116062568737695
Error :0.3417983096292012
Error :0.3310109815219128
Error :0.31852802913540007
Error :0.3119178028970372
Error :0.3070082211548975
Error :0.30293555391932087
Error :0.2983190494287253
Error :0.29457412534782385


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:33<00:24,  8.10s/dim]

Error :0.2921649000718168
Error :1.0
Error :0.44498756659213007
Error :0.3848268432467654
Error :0.35142197851365553
Error :0.33069126945513455
Error :0.31749323404418245
Error :0.30698375794434457
Error :0.29719067535789045
Error :0.2927388491681241
Error :0.2859641435138671
Error :0.2826018300679951
Error :0.27824311269435364
Error :0.2748880685024226
Error :0.2715946848932794
Error :0.2681403867019496


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:47<00:19,  9.98s/dim]

Error :0.26398106965350915
Error :1.0
Error :0.44279416980407044
Error :0.37923363448659664
Error :0.3440167831379056
Error :0.32292785867353924
Error :0.307877185750245
Error :0.2967014637546484
Error :0.28810432646597506
Error :0.27994600516942664
Error :0.2744675654994185
Error :0.27055190352867947
Error :0.2642918400551491
Error :0.2598775264645975
Error :0.25808192878075126
Error :0.2539163713351309
Error :0.25225196696267727
Error :0.24935237302305727


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [01:04<00:12, 12.29s/dim]

Error :0.24690703397789213
Error :1.0
Error :0.4400219043245242
Error :0.3753707347767916
Error :0.33893857739840394
Error :0.3164721037825935
Error :0.30096231181174415
Error :0.28817961802458164
Error :0.27973082797267634
Error :0.2728311290375291
Error :0.2642770454929916
Error :0.2592156425831066
Error :0.2551963384118043
Error :0.25054973584418316
Error :0.24678342659388586
Error :0.24282890723954353
Error :0.23925911424154342
Error :0.2366007874697144
Error :0.233739336145795
Error :0.23147159452792765
Error :0.22912308790803715


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:22<00:00, 10.37s/dim]


Error :0.22724769751369708
Results saved to ../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_32.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.9614686953527921


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:16,  2.35s/dim]

Error :0.9486128109628859
Error :1.0
Error :0.9449842810904242
Error :0.9284153048471849
Error :0.9150702341895847
Error :0.9032443937295132


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:07<00:22,  3.83s/dim]

Error :0.8960303601176378
Error :1.0
Error :0.9331526446677065
Error :0.9140311963488631
Error :0.90035258843897
Error :0.8866104004108493
Error :0.8750145651447063
Error :0.8664436819384398


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:13<00:25,  5.06s/dim]

Error :0.8568163232464047
Error :1.0
Error :0.9259244719876063
Error :0.9022376459357233
Error :0.8871279138943254
Error :0.8738312387011662
Error :0.8630082597871362
Error :0.8508442688299308
Error :0.8432382072358771
Error :0.8324181029756726
Error :0.8226776888497281


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:23<00:27,  6.75s/dim]

Error :0.8185521694400855
Error :1.0
Error :0.9211014555561228
Error :0.894322901006355
Error :0.876888073195064
Error :0.8640654791370312
Error :0.850111346662717
Error :0.8386906474638188
Error :0.8301101771750284
Error :0.8187021313126635
Error :0.8079088989315635
Error :0.8020253431375847
Error :0.7958309389959877


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:33<00:24,  8.06s/dim]

Error :0.7843288000594578
Error :1.0
Error :0.9146912684121382
Error :0.887645707037001
Error :0.8692772457767886
Error :0.8546212524535939
Error :0.8411651141028998
Error :0.8301290201935843
Error :0.8160953606142327
Error :0.8079548068456935
Error :0.8003624842159817
Error :0.7873690417298869
Error :0.7798676730461485
Error :0.7737390387009234
Error :0.7669784128999482
Error :0.7585695720489126


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:46<00:19,  9.84s/dim]

Error :0.75316878642084
Error :1.0
Error :0.9120348989672447
Error :0.8836442288371126
Error :0.8634565136921557
Error :0.8466588503357066
Error :0.8326088396557597
Error :0.8208755029743063
Error :0.8103154163255232
Error :0.798062229170577
Error :0.7895053568077112
Error :0.7783601328851252
Error :0.7709006196601563
Error :0.7625464194933022
Error :0.7542559542763525
Error :0.7444305783978667
Error :0.7402040256840519
Error :0.7302362575147004


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [01:01<00:11, 11.39s/dim]

Error :0.7269405690535026
Error :1.0
Error :0.9076774176629319
Error :0.8778177497173584
Error :0.8567311550664282
Error :0.8409244170117516
Error :0.8258412053084775
Error :0.8136769577959041
Error :0.8017672182140022
Error :0.7905111956498051
Error :0.7786042595608454
Error :0.7708913257651425
Error :0.7595430905337981
Error :0.7532303296396705
Error :0.7430111751015465
Error :0.7349414014634679
Error :0.7276149386712303
Error :0.7193726265516726
Error :0.7146617037448411
Error :0.7065921801102266
Error :0.7027054859764769


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:18<00:00,  9.83s/dim]


Error :0.6931679578772149
Results saved to ../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_1.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.20883377444437415


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:17,  2.53s/dim]

Error :0.08440666054823938
Error :1.0
Error :0.15379479166387808
Error :0.07145836849513704
Error :0.0778651093715297
Error :0.008774217805612071


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:07<00:22,  3.70s/dim]

Error :0.013650984765621271
Error :1.0
Error :0.13939233971634588
Error :0.013856040723863058
Error :0.004198313032590679
Error :0.004674237178847396
Error :0.03510730195526154
Error :0.0036379776651955546


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:12<00:23,  4.71s/dim]

Error :0.005473116203192558
Error :1.0
Error :0.13972042301212403
Error :0.017000309242943334
Error :0.0026729466231782072
Error :0.00030187424888269504
Error :0.0015421007997836764
Error :7.166418916747297e-05
Error :0.0016394700109655523
Error :7.526621707603713e-05
Error :0.003149910763750305


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:21<00:24,  6.17s/dim]

Error :0.0003071919307450378
Error :1.0
Error :0.1378142470524851
Error :0.013795721320058088
Error :0.0026545517539111776
Error :0.0016284891716732948
Error :0.0031298649296114464
Error :5.679257419190195e-05
Error :0.0014911547762124812
Error :0.001494380654001083
Error :0.0014982553935001632
Error :0.0015425628462345457
Error :0.0015333124818182138


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:31<00:22,  7.59s/dim]

Error :2.1496116040942326e-05
Error :1.0
Error :0.13781504543298118
Error :0.013788371613898374
Error :0.0014159684739702613
Error :0.0001414730887424233
Error :2.5129709334857036e-05
Error :1.5118491405044879e-05
Error :5.744807939748931e-05
Error :2.26061922864223e-05
Error :0.0015006345290198588
Error :5.9931545048151685e-05
Error :0.0014914358063944566
Error :4.243064835637738e-05
Error :1.0152177595927724e-05
Error :1.4171656132591093e-05


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:44<00:18,  9.34s/dim]

Error :7.934815219296302e-06
Error :1.0
Error :0.13781364949046374
Error :0.014664411379010873
Error :0.001382455504062158
Error :0.0001659427720010347
Error :2.1061814417067724e-05
Error :6.5242180280539025e-06
Error :1.4243854414737963e-05
Error :3.851107091475718e-06
Error :4.518004271700398e-05
Error :0.0014864836749384517
Error :0.001482650135070276
Error :1.2457369830085567e-05
Error :7.966876895550978e-06
Error :9.21394589270183e-06
Error :9.97595476375852e-06
Error :1.1778439740232281e-05


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [00:59<00:11, 11.37s/dim]

Error :3.7922384680522006e-06
Error :1.0
Error :0.13781256566747402
Error :0.013781227896318646
Error :0.0013798814289402415
Error :0.00014141310007194502
Error :1.3784439572745737e-05
Error :3.0488978484606436e-06
Error :4.192078114343312e-06
Error :3.7848096829984523e-06
Error :5.7096948558719055e-06
Error :4.119119072746805e-06
Error :6.369930048191685e-06
Error :1.8959334233975654e-06
Error :5.690754939811443e-06
Error :4.493203675147259e-06
Error :5.9787593493709454e-06
Error :2.8964982993719184e-09
Error :3.946549145252512e-06
Error :8.801122316280243e-09
Error :9.842874965646651e-06


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:17<00:00,  9.72s/dim]


Error :5.9792859205447195e-06
Results saved to ../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_2.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.006742121462662463


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:20,  2.88s/dim]

Error :0.006039814040589963
Error :1.0
Error :0.005845708253779097
Error :0.004583838594490886
Error :0.003990091946752947
Error :0.003666230625235584


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:07<00:24,  4.08s/dim]

Error :0.0035950812689580784
Error :1.0
Error :0.005585827749146972
Error :0.00409950401199161
Error :0.0033857481273540176
Error :0.0029786377468615922
Error :0.0028190553507714067
Error :0.0025893148014647207


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:14<00:27,  5.49s/dim]

Error :0.002563459422834933
Error :1.0
Error :0.005438555428546793
Error :0.0038980246887716364
Error :0.0031151885886194636
Error :0.00263005743592148
Error :0.0023690705560446444
Error :0.002159959124215242
Error :0.0020373913358630175
Error :0.001955917715843185
Error :0.001907579036263518


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:24<00:28,  7.20s/dim]

Error :0.0018183910553107759
Error :1.0
Error :0.005395981432709752
Error :0.003796351355418407
Error :0.0029510797442499647
Error :0.002432715383494022
Error :0.0021291307906902523
Error :0.0019020534166603181
Error :0.0017616274218506835
Error :0.0016538150973577522
Error :0.0015560515099887831
Error :0.001519156846303057
Error :0.0014667236204583278


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:36<00:26,  8.91s/dim]

Error :0.0014565052784778426
Error :1.0
Error :0.00535700911746169
Error :0.0037314700285708286
Error :0.0028690629051582764
Error :0.002328732233474832
Error :0.002004193597369114
Error :0.0017476414145068586
Error :0.001608664477607673
Error :0.0014588025460538989
Error :0.0013858936094310837
Error :0.0013135950666817594
Error :0.0012419869288012595
Error :0.0012144087982087274
Error :0.0011725956003527638
Error :0.0011526097693042158


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:51<00:21, 10.90s/dim]

Error :0.0011192334144679238
Error :1.0
Error :0.005330099430829031
Error :0.003683734549184435
Error :0.002800860610630813
Error :0.0022602253004689434
Error :0.001907260519005854
Error :0.0016506912179279892
Error :0.0014753152332680276
Error :0.0013368605198757866
Error :0.001239282910864795
Error :0.0011687824230401918
Error :0.0011123439928591567
Error :0.0010448723004897274
Error :0.0010231656968833192
Error :0.0009838570501562844
Error :0.0009427600855802336
Error :0.0009275698495664928


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [01:07<00:12, 12.70s/dim]

Error :0.0009061278048273999
Error :1.0
Error :0.005313910590174652
Error :0.003656377992748649
Error :0.0027693551084712123
Error :0.002206207961274082
Error :0.001842294445460913
Error :0.0015862328418123292
Error :0.0014003538272841889
Error :0.001247098155833056
Error :0.001147391890103909
Error :0.0010602138219801731
Error :0.0010053532883067648
Error :0.000944311473006781
Error :0.0008913208353687781
Error :0.0008648771801068688
Error :0.0008357362388343703
Error :0.0008078019504483149
Error :0.0007806394323331812
Error :0.0007588726727831885
Error :0.0007494203497187356


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:28<00:00, 11.01s/dim]


Error :0.0007351679383409761
Results saved to ../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_3.csv.
(1024, 1024)


Sketch Dimensions Progress:   0%|          | 0/8 [00:00<?, ?dim/s]

Error :1.0
Error :0.5306783787477702


Sketch Dimensions Progress:  12%|█▎        | 1/8 [00:02<00:19,  2.77s/dim]

Error :0.503601887682963
Error :1.0
Error :0.48861237835066873
Error :0.4492214659250697
Error :0.43029986658499414
Error :0.42209998036420704


Sketch Dimensions Progress:  25%|██▌       | 2/8 [00:07<00:24,  4.15s/dim]

Error :0.411083141784923
Error :1.0
Error :0.46568373259676343
Error :0.4174718662214034
Error :0.3895812679603547
Error :0.3781417001702485
Error :0.37148530735927676
Error :0.36202510174795344


Sketch Dimensions Progress:  38%|███▊      | 3/8 [00:15<00:27,  5.52s/dim]

Error :0.3571349696334534
Error :1.0
Error :0.456452760799546
Error :0.4012384167984704
Error :0.37443002988598817
Error :0.35662815813992155
Error :0.3440565372498238
Error :0.33712436425300185
Error :0.3305041638565651
Error :0.32659398155940533
Error :0.3215934974373959


Sketch Dimensions Progress:  50%|█████     | 4/8 [00:25<00:29,  7.33s/dim]

Error :0.31887537245020225
Error :1.0
Error :0.4504121713917545
Error :0.3911534907099274
Error :0.35886130054818205
Error :0.342076949045056
Error :0.32736251261351135
Error :0.3194257498788924
Error :0.31152573041838505
Error :0.30566930118427704
Error :0.3025902611621111
Error :0.2969011386223157
Error :0.2955615248040132


Sketch Dimensions Progress:  62%|██████▎   | 5/8 [00:37<00:27,  9.18s/dim]

Error :0.29138928310386353
Error :1.0
Error :0.4462211772868873
Error :0.38487076491979905
Error :0.3526126593294573
Error :0.33104360999516375
Error :0.3178601085830122
Error :0.30512791506888703
Error :0.29865528824755666
Error :0.29072277874041563
Error :0.2868755091548704
Error :0.28277395698464847
Error :0.276158957036716
Error :0.2758131845166162
Error :0.27226025653205144
Error :0.2680672815301619


Sketch Dimensions Progress:  75%|███████▌  | 6/8 [00:54<00:23, 11.66s/dim]

Error :0.2648849341739228
Error :1.0
Error :0.4423111278049151
Error :0.37813234833308895
Error :0.3457365035981818
Error :0.32234633283191655
Error :0.3077213296094297
Error :0.29693764327538086
Error :0.2869815978751995
Error :0.2805987477453641
Error :0.2752198548731282
Error :0.2685478096988795
Error :0.2655631528373714
Error :0.259937345314048
Error :0.25850345421183585
Error :0.25466924969084853
Error :0.24978515415065078
Error :0.2486658726731785


Sketch Dimensions Progress:  88%|████████▊ | 7/8 [01:12<00:13, 13.78s/dim]

Error :0.24673348280808957
Error :1.0
Error :0.440259205966917
Error :0.37447785715735804
Error :0.3392182432153556
Error :0.3168355235340421
Error :0.301895986725637
Error :0.28943538194889584
Error :0.27943918475682966
Error :0.2723572240924201
Error :0.26595044092839026
Error :0.26009096612751537
Error :0.2547632622878583
Error :0.2493346006713285
Error :0.24690018983007764
Error :0.24348498691639234
Error :0.23914751276382837
Error :0.2361788983115978
Error :0.23521218456190301
Error :0.23129575839463504
Error :0.22878378281242467


Sketch Dimensions Progress: 100%|██████████| 8/8 [01:32<00:00, 11.61s/dim]

Error :0.22724330245067237
Results saved to ../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_32.csv.


### Diagram 

In the following parts, we'll draw diagrams. 

In [28]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

def plot_statistical_diagram_with_logscale(csv_file, save_path, include_labels=True):
    """
    Plots a statistical diagram comparing error values with approximation rank for different sketch dimensions.
    Uses a logarithmic scale for error values.
    
    Parameters:
        csv_file (str): Path to the .csv file containing the data.
        save_path (str): File path to save the resulting plot.
        include_labels (bool): If True, includes axis labels and a legend. If False, no labels or legend will be displayed.
    """
    # Load the CSV data
    data = pd.read_csv(csv_file)
    
    # Initialize the Seaborn style
    sns.set(style="whitegrid")
    
    # Create the line plot
    plt.figure(figsize=(10, 6))
    sns.lineplot(
        data=data,
        x="Approximation Rank",
        y="Error Value",
        hue="Sketch Dimension",
        style="Sketch Dimension",
        markers=True,
        dashes=False,
        palette="deep"
    )
    
    # Use log scale for the y-axis (Error Value)
    plt.yscale('log')
    
    # Set axis labels and title if needed
    if include_labels:
        plt.title("Error (Log Scale) vs Approximation Rank for Different Sketch Dimensions", fontsize=14)
        plt.xlabel("Approximation Rank", fontsize=12)
        plt.ylabel("Error Value (Log Scale)", fontsize=12)
        plt.legend(title="Sketch Dimension", fontsize=10)
    else:
        plt.axis("off")
    
    # Save the plot
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()
    print(f"Plot saved at {save_path}")

# Example usage:
# plot_statistical_diagram_with_logscale("Section_2_test_3_Gaussian_for_loadMatrixA_1.csv", "error_vs_rank_logscale.png", include_labels=True)


In [31]:
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_1.csv", "error_vs_rank_A_1_Gaussian.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_2.csv", "error_vs_rank_A_2_Gaussian.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_3.csv", "error_vs_rank_A_3_Gaussian.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_3_Gaussian_for_loadMatrixA_32.csv", "error_vs_rank_A_32_Gaussian.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_1.csv", "error_vs_rank_A_1_fjlt.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_2.csv", "error_vs_rank_A_2_fjlt.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_3.csv", "error_vs_rank_A_3_fjlt.png", include_labels=True)
plot_statistical_diagram_with_logscale("../Dataset/Section_2_test_4_fjlt_for_loadMatrixA_32.csv", "error_vs_rank_A_32_fjlt.png", include_labels=True)


Plot saved at error_vs_rank_A_1_Gaussian.png
Plot saved at error_vs_rank_A_2_Gaussian.png
Plot saved at error_vs_rank_A_3_Gaussian.png
Plot saved at error_vs_rank_A_32_Gaussian.png
Plot saved at error_vs_rank_A_1_fjlt.png
Plot saved at error_vs_rank_A_2_fjlt.png
Plot saved at error_vs_rank_A_3_fjlt.png
Plot saved at error_vs_rank_A_32_fjlt.png
